apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Values.nameOverride }}-backtester"
  labels:
    app.kubernetes.io/name: backtester
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: 1.16.0
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: webistecs
    app.kubernetes.io/managed-by: Helm
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backtester
        app.kubernetes.io/instance: release-name
    spec:
      restartPolicy: Never
      containers:
        - name: backtester
          image: "{{ .Values.backtester.image.repository }}:{{ .Values.backtester.image.tag }}"
          imagePullPolicy: "{{ .Values.backtester.image.pullPolicy }}"
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "{{ .Values.backtester.environment.aspNetCoreEnvironment }}"
            - name: DB_CONTEXT
              value: "WebistecsContext"
            - name: DATA_DIR
              value: "{{ .Values.backtester.dataDir }}"
            - name: BacktestParameters__Year
              value: "{{ .Values.backtester.year }}"
            - name: BacktestParameters__Month
              value: "{{ .Values.backtester.month }}"
            - name: BacktestParameters__InitialUsdc
              value: "{{ .Values.backtester.initialUsdc }}"
            - name: BacktestParameters__Strategy
              value: "{{ .Values.backtester.strategy }}"
            - name: ConnectionStrings__WebistecsContext
              value: "{{ .Values.backtester.environment.webistecsContext }}"
            - name: FEE
              value: "{{ .Values.backtester.fee }}"
            - name: SAFETY_MARGIN
              value: "{{ .Values.backtester.safetyMargin }}"
            - name: Combo_Upper_Start
              value: "{{ .Values.backtester.combo.upper.start }}"
            - name: Combo_Upper_End
              value: "{{ .Values.backtester.combo.upper.endValue }}"
            - name: Combo_Upper_Target
              value: "{{ .Values.backtester.combo.upper.target }}"
            - name: Combo_Upper_Weight
              value: "{{ .Values.backtester.combo.upper.weight }}"
            - name: Combo_Upper_Tier
              value: "{{ .Values.backtester.combo.upper.tier }}"
            - name: Combo_Middle_Start
              value: "{{ .Values.backtester.combo.middle.start }}"
            - name: Combo_Middle_End
              value: "{{ .Values.backtester.combo.middle.endValue }}"
            - name: Combo_Middle_Target
              value: "{{ .Values.backtester.combo.middle.target }}"
            - name: Combo_Middle_Weight
              value: "{{ .Values.backtester.combo.middle.weight }}"
            - name: Combo_Middle_Tier
              value: "{{ .Values.backtester.combo.middle.tier }}"
            - name: Combo_Lower_Start
              value: "{{ .Values.backtester.combo.lower.start }}"
            - name: Combo_Lower_End
              value: "{{ .Values.backtester.combo.lower.endValue }}"
            - name: Combo_Lower_Target
              value: "{{ .Values.backtester.combo.lower.target }}"
            - name: Combo_Lower_Weight
              value: "{{ .Values.backtester.combo.lower.weight }}"
            - name: Combo_Lower_Tier
              value: "{{ .Values.backtester.combo.lower.tier }}"
          resources:
            limits:
              cpu: "{{ .Values.backtester.resources.limits.cpu }}"
              memory: "{{ .Values.backtester.resources.limits.memory }}"
            requests:
              cpu: "{{ .Values.backtester.resources.requests.cpu }}"
              memory: "{{ .Values.backtester.resources.requests.memory }}"
          volumeMounts:
            - name: pricedata-volume
              mountPath: /app/pricedata
            - name: result-volume
              mountPath: /app/backtest-results
      volumes:
        - name: pricedata-volume
          persistentVolumeClaim:
            claimName: "{{ .Values.backtester.pvc }}"
        - name: result-volume
          persistentVolumeClaim:
            claimName: "backtest-results-pvc"