apiVersion: batch/v1
kind: Job
metadata:
  name: backtester-manual-run
  namespace: default
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: backtester-manual-run
    spec:
      restartPolicy: OnFailure  # Changed from Never to allow retries
      containers:
        - name: backtester
          image: emabhiza/webistecs-backtest:test-0.0.2
          imagePullPolicy: IfNotPresent
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: LOCAL_RESULTS_PATH  # New env var for C# code
              value: "/host-output"
            - name: BacktestParameters__Year
              value: "2022"
            - name: BacktestParameters__Month
              value: "1"
            - name: BacktestParameters__InitialUsdc
              value: "1000"
            - name: BacktestParameters__Strategy
              value: "MacroUptrend"
          volumeMounts:
            - name: pricedata-volume
              mountPath: /app/Resources
              readOnly: true
            - name: result-volume
              mountPath: /app/backtest-results
            - name: host-results  # New mount for Mac access
              mountPath: /host-output
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"  # Increased from 512Mi
            requests:
              cpu: "250m"
              memory: "512Mi"  # Increased from 256Mi
      volumes:
        - name: pricedata-volume
          persistentVolumeClaim:
            claimName: pricedata-test-pvc
        - name: result-volume
          persistentVolumeClaim:
            claimName: backtest-results-pvc
        - name: host-results  # New volume for Mac
          hostPath:
            path: /Users/emabhiza/Dev/webistecs-storage/backtest-results
            type: DirectoryOrCreate