{{- if .Values.backtester.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webistecs.fullname" . }}-backtester
  labels:
    {{- include "webistecs.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "webistecs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "webistecs.selectorLabels" . | nindent 8 }}
    spec:
      nodeSelector:
        kubernetes.io/hostname: pi4-c7a9e0e0
      containers:
        - name: backtester
          image: "{{ .Values.backtester.image.repository }}:{{ .Values.backtester.image.tag }}"
          imagePullPolicy: {{ .Values.backtester.image.pullPolicy }}
          
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Backtest
            - name: SKIP_MIGRATIONS
              value: "true"
            - name: DB_CONTEXT
              value: "WebistecsContext"
            - name: DATA_DIR
              value: "{{ .Values.backtester.dataDir }}"
            - name: BacktestParameters__Year
              value: "{{ .Values.backtester.year }}"
            - name: BacktestParameters__Month
              value: "{{ .Values.backtester.month }}"
            - name: BacktestParameters__InitialUsdc
              value: "{{ .Values.backtester.initialUsdc | default "100" }}"
            - name: BacktestParameters__Strategy
              value: "{{ .Values.backtester.strategy | default "MacroUptrend" }}"
            - name: ConnectionStrings__WebistecsContext
              value: "{{ .Values.backtester.environment.webistecsContext }}"
          resources:
            {{- toYaml .Values.backtester.resources | nindent 12 }}
          volumeMounts:
            - name: pricadata-volume
              mountPath: {{ .Values.backtester.dataDir }}
            - name: db-volume
              mountPath: /db
      volumes:
        - name: pricadata-volume
          persistentVolumeClaim:
            claimName: {{ .Values.backtester.pvc }}
        - name: db-volume
          persistentVolumeClaim:
            claimName: {{ .Values.dbMigrationJob.volumeClaimName }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
{{- end }}
