apiVersion: apps/v1
kind: Deployment
metadata:
  name: backtest-{{ include "webistecs.fullname" . }}
  labels:
    app: backtester
  annotations:
    checksum/config: "{{ printf "%s:%s" .Values.backtester.image.repository .Values.backtester.image.tag | sha256sum }}"
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-weight: "10"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backtester
  template:
    metadata:
      labels:
        app: backtester
    spec:
      containers:
        - name: backtester
          image: "{{ .Values.backtester.image.repository }}:{{ .Values.backtester.image.tag }}"
          imagePullPolicy: Always
          env:
            - name: DATA_DIR
              value: "{{ .Values.backtester.dataDir }}"
            - name: year
              value: "{{ .Values.backtester.year }}"
            - name: ConnectionStrings__WebistecsContext
              value: "{{ .Values.backtester.environment.webistecsContext }}"
            - name: DB_CONTEXT
              value: "WebistecsContext"
          resources:
            requests:
              ephemeral-storage: "100Mi"
            limits:
              ephemeral-storage: "300Mi"
          volumeMounts:
            - name: pricadata-volume
              mountPath: {{ .Values.backtester.dataDir }}
      volumes:
        - name: pricadata-volume
          persistentVolumeClaim:
            claimName: {{ .Values.backtester.pvc }}
      restartPolicy: Always
      imagePullSecrets:
        - name: {{ .Values.webistecs.imagePullSecret }}
