apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webistecs.fullname" . }}-backtester
  labels:
    {{- include "webistecs.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "webistecs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "webistecs.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: backtester
          command: [ "/bin/sh", "-c" ]
          args:
            - ls -lh /db && ls -lh /app && ls -lh && your-original-command
          image: "{{ .Values.backtester.image.repository }}:{{ .Values.backtester.image.tag }}"
          imagePullPolicy: {{ .Values.backtester.image.pullPolicy }}
          env:
            - name: DATA_DIR
              value: "{{ .Values.backtester.dataDir }}"
            - name: year
              value: "{{ .Values.backtester.year }}"
            - name: ConnectionStrings__WebistecsContext
              value: "{{ .Values.backtester.environment.webistecsContext }}"
          resources:
          {{- toYaml .Values.backtester.resources | nindent 10 }}
          volumeMounts:
            - name: pricadata-volume
              mountPath: {{ .Values.backtester.dataDir }}
      volumes:
        - name: pricadata-volume
          persistentVolumeClaim:
            claimName: {{ .Values.backtester.pvc }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}