apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "webistecs.fullname" . }}-migration
  annotations:
    checksum/config: "{{ printf "%s:%s" .Values.webistecs.image.repository .Values.webistecs.image.tag | sha256sum }}"
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-weight: "5"
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: migration
          image: "{{ .Values.dbMigrationJob.image.repository }}:{{ .Values.dbMigrationJob.image.tag }}"
          imagePullPolicy: Always
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "{{ .Values.dbMigrationJob.environment.aspNetCoreEnvironment }}"
            - name: ConnectionStrings__WebistecsContext
              value: "{{ .Values.dbMigrationJob.environment.webistecsContext }}"
            - name: DB_CONTEXT
              value: "WebistecsContext"
            - name: SKIP_MIGRATIONS
              value: "{{ .Values.dbMigrationJob.environment.SKIP_MIGRATIONS }}"
          resources:
            requests:
              memory: "{{ .Values.dbMigrationJob.resources.requests.memory }}"
              cpu: "{{ .Values.dbMigrationJob.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.dbMigrationJob.resources.limits.memory }}"
              cpu: "{{ .Values.dbMigrationJob.resources.limits.cpu }}"
      imagePullSecrets:
        - name: {{ .Values.webistecs.imagePullSecret }}
      restartPolicy: Never
