apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "webistecs.fullname" . }}-migration
  annotations:
    checksum/config: "{{ printf "%s:%s" .Values.webistecs.image.repository .Values.webistecs.image.tag | sha256sum }}"
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-weight: "5"
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: migration
          image: "{{ .Values.dbMigrationJob.image.repository }}:{{ .Values.dbMigrationJob.image.tag }}"
          imagePullPolicy: Always
          env:
            - name: environmentVariables__ASPNETCORE__ENVIRONMENT
              value: "Production"
            - name: environmentVariables__ASPNETCORE_TYPE
              value: "BESTIE"
            - name: environmentVariables__ASPNETCORE__TYPE
              value: "TESTIE"
            - name: APPLICATION__EnvironmentType
              value: "Production"
            - name: ASPNETCORE__ENVIRONMENT
              value: "{{ .Values.dbMigrationJob.environment.aspNetCoreEnvironment }}"
            - name: ConnectionStrings__WebistecsContext
              value: "{{ .Values.dbMigrationJob.environment.webistecsContext }}"
            - name: GRAFANA__URL
              value: "http://192.168.68.107:32100"
            - name: LOKI__URL
              value: "https://log-api.eu.newrelic.com/log/v1"
            - name: NEWRELIC__APIKEY
              valueFrom:
                secretKeyRef:
                  name: webistecs-secret
                  key: NEWRELIC__APIKEY
            - name: TELEGRAM__NOTIFICATIONS
              valueFrom:
                secretKeyRef:
                  name: webistecs-secret
                  key: TELEGRAM__NOTIFICATIONS
            - name: TELEGRAM__ERRORS
              valueFrom:
                secretKeyRef:
                  name: webistecs-secret
                  key: TELEGRAM__ERRORS
            - name: TELEGRAM__FUNCTIONS
              valueFrom:
                secretKeyRef:
                  name: webistecs-secret
                  key: TELEGRAM__FUNCTIONS
            - name: TELEGRAM__LISTENER_ID
              valueFrom:
                secretKeyRef:
                  name: webistecs-secret
                  key: TELEGRAM__LISTENER_ID
            - name: TELEGRAM__API_HASH
              valueFrom:
                secretKeyRef:
                  name: webistecs-secret
                  key: TELEGRAM__API_HASH
            - name: TELEGRAM__FUNCTIONS_HASH
              valueFrom:
                secretKeyRef:
                  name: webistecs-secret
                  key: TELEGRAM__FUNCTIONS_HASH
            - name: TELEGRAM__PHONE_NUMBER
              valueFrom:
                secretKeyRef:
                  name: webistecs-secret
                  key: TELEGRAM__PHONE_NUMBER
            - name: TELEGRAM__RELEASES
              valueFrom:
                secretKeyRef:
                  name: webistecs-secret
                  key: TELEGRAM__RELEASES

            - name: TELEGRAM_CHANNELS
              value: '[
                  {"Type": "Notifications", "Id": "$(TELEGRAM__NOTIFICATIONS)"},
                  {"Type": "Errors", "Id": "$(TELEGRAM__ERRORS)"},
                  {"Type": "Functions", "Id": "$(TELEGRAM__FUNCTIONS)"},
                  {"Type": "Releases", "Id": "$(TELEGRAM__RELEASES)"}
              ]'

            - name: TELEGRAM_LISTENER
              value: '{
                  "Id": "$(TELEGRAM__LISTENER_ID)",
                  "Hash": "$(TELEGRAM__API_HASH)",
                  "PhoneNumber": "$(TELEGRAM__PHONE_NUMBER)"
              }'

          resources:
            requests:
              memory: "{{ .Values.dbMigrationJob.resources.requests.memory }}"
              cpu: "{{ .Values.dbMigrationJob.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.dbMigrationJob.resources.limits.memory }}"
              cpu: "{{ .Values.dbMigrationJob.resources.limits.cpu }}"
          volumeMounts:
            - name: db-storage
              mountPath: /db
      imagePullSecrets:
        - name: {{ .Values.webistecs.imagePullSecret }}
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: webistecs-db-pvc
      restartPolicy: Never