apiVersion: v1
kind: Pod
metadata:
  name: webistecs-debug
  namespace: default
spec:
  containers:
    - name: debug-container
      image: busybox
      command: ["sleep", "3600"]  # Keeps the container running
      envFrom:
        - secretRef:
            name: webistecs-secret  # Mounts secrets as environment variables
      volumeMounts:
        - name: db-volume
          mountPath: /db  # Mounts the same volume used by the main application
  volumes:
    - name: db-volume
      persistentVolumeClaim:
        claimName: webistecs-db-pvc  # Uses the same PVC as the main application
  restartPolicy: Never


