{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webistecs.fullname" . }}
  labels:
    {{- include "webistecs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 8000 }}
      targetPort: {{ .Values.webistecs.containerPort | default 80 }}
      protocol: TCP
  selector:
    {{- include "webistecs.selectorLabels" . | nindent 4 }}
{{- end }}