{{- /*
This template works with both:
1. Production setup (service config at root .Values)
2. Backtester jobs (service config under .Values.backtester)
*/ -}}

{{- $service := .Values.service -}}
{{- if .Values.backtester -}}
  {{- if .Values.backtester.service -}}
    {{- $service = .Values.backtester.service -}}
  {{- end -}}
{{- end -}}

{{- if $service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webistecs.fullname" . }}
  labels:
    {{- include "webistecs.labels" . | nindent 4 }}
spec:
  type: {{ $service.type | default "ClusterIP" }}
  ports:
    - port: {{ $service.port | default 8000 }}
      targetPort: {{ $.Values.webistecs.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "webistecs.selectorLabels" . | nindent 4 }}
{{- end }}