apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride }}
  labels:
    {{- include "webistecs.labels" . | nindent 4 }}
    environment: {{ .Values.webistecs.environment.aspNetCoreEnvironment | lower }}
spec:
  type: NodePort
  ports:
    - name: "http"
      port: 8000
      targetPort: {{ .Values.webistecs.containerPort }}
      {{- if eq .Values.webistecs.environment.aspNetCoreEnvironment "Production" }}
      nodePort: 30080
      {{- else }}
      nodePort: 30081
      {{- end }}
      protocol: TCP
  selector:
    {{- include "webistecs.selectorLabels" . | nindent 4 }}
    environment: {{ .Values.webistecs.environment.aspNetCoreEnvironment | lower }}
