apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webistecs.fullname" . }}
  annotations:
    checksum/config: "{{ printf "%s:%s" .Values.webistecs.image.repository .Values.webistecs.image.tag | sha256sum }}"
spec:
  replicas: {{ .Values.webistecs.replicaCount }}
  selector:
    matchLabels:
      {{- include "webistecs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "webistecs.selectorLabels" . | nindent 8 }}
      annotations:
        co.elastic.logs/enabled: {{ .Values.webistecs.logging.enabled | quote }}
        co.elastic.logs/module: {{ .Values.webistecs.logging.module | quote }}
        co.elastic.logs/fileset.stdout: {{ .Values.webistecs.logging.fileset.stdout | quote }}
        co.elastic.logs/fileset.stderr: {{ .Values.webistecs.logging.fileset.stderr | quote }}
        checksum/config: "{{ printf "%s:%s" .Values.webistecs.image.repository .Values.webistecs.image.tag | sha256sum }}"
    spec:
      containers:
        - name: {{ .Values.webistecs.containerName }}
          image: "{{ .Values.webistecs.image.repository }}:{{ .Values.webistecs.image.tag }}"
          imagePullPolicy: {{ .Values.webistecs.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.webistecs.containerPort }}
          readinessProbe:
            httpGet:
              path: {{ .Values.webistecs.readinessProbe.path }}
              port: {{ .Values.webistecs.readinessProbe.port }}
            initialDelaySeconds: {{ .Values.webistecs.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.webistecs.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.webistecs.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.webistecs.readinessProbe.successThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .Values.webistecs.livenessProbe.path }}
              port: {{ .Values.webistecs.livenessProbe.port }}
            initialDelaySeconds: {{ .Values.webistecs.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.webistecs.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.webistecs.livenessProbe.failureThreshold }}
          env:
            - name: ASPNETCORE__ENVIRONMENT
              value: "{{ .Values.webistecs.environment.aspNetCoreEnvironment }}"
            - name: COINBASE__PRIVATEKEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.webistecs.secrets.webistecsSecret }}
                  key: {{ .Values.webistecs.secrets.coinbase__privateKey }}
            - name: COINBASE__PRIVATEKEYNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.webistecs.secrets.webistecsSecret }}
                  key: {{ .Values.webistecs.secrets.coinbase__privateName }}
            - name: ConnectionStrings__WebistecsContext
              value: "{{ .Values.webistecs.environment.webistecsContext }}"
          resources:
            requests:
              memory: "{{ .Values.webistecs.resources.requests.memory }}"
              cpu: "{{ .Values.webistecs.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.webistecs.resources.limits.memory }}"
              cpu: "{{ .Values.webistecs.resources.limits.cpu }}"
          volumeMounts:
            - name: db-volume
              mountPath: {{ .Values.webistecs.volumeMountPath }}
        - name: {{ .Values.nodeExporter.name }}
          image: "{{ .Values.nodeExporter.image }}"
          ports:
            - containerPort: {{ .Values.nodeExporter.containerPort }}
      restartPolicy: {{ .Values.webistecs.restartPolicy }}
      imagePullSecrets:
        - name: {{ .Values.webistecs.imagePullSecret }}
      volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName: {{ .Values.webistecs.volume.persistentVolumeClaim.claimName }}