apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webistecs.fullname" . }}
  annotations:
    checksum/config: "{{ printf "%s:%s" .Values.webistecs.image.repository .Values.webistecs.image.tag | sha256sum }}"
spec:
  replicas: {{ .Values.webistecs.replicaCount }}
  selector:
    matchLabels:
      {{- include "webistecs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "webistecs.selectorLabels" . | nindent 8 }}
      annotations:
        co.elastic.logs/enabled: {{ .Values.webistecs.logging.enabled | quote }}
        co.elastic.logs/module: {{ .Values.webistecs.logging.module | quote }}
        co.elastic.logs/fileset.stdout: {{ .Values.webistecs.logging.fileset.stdout | quote }}
        co.elastic.logs/fileset.stderr: {{ .Values.webistecs.logging.fileset.stderr | quote }}
        checksum/config: "{{ printf "%s:%s" .Values.webistecs.image.repository .Values.webistecs.image.tag | sha256sum }}"
    spec:
      containers:
        - name: {{ .Values.webistecs.containerName }}
          image: "{{ .Values.webistecs.image.repository }}:{{ .Values.webistecs.image.tag }}"
          imagePullPolicy: {{ .Values.webistecs.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.webistecs.containerPort }}
          readinessProbe:
            httpGet:
              path: {{ .Values.webistecs.readinessProbe.path }}
              port: {{ .Values.webistecs.readinessProbe.port }}
            initialDelaySeconds: {{ .Values.webistecs.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.webistecs.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.webistecs.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.webistecs.readinessProbe.successThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .Values.webistecs.livenessProbe.path }}
              port: {{ .Values.webistecs.livenessProbe.port }}
            initialDelaySeconds: {{ .Values.webistecs.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.webistecs.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.webistecs.livenessProbe.failureThreshold }}
          env:
            - name: APPLICATION__EnvironmentType
              value: "Production"
            - name: ASPNETCORE__ENVIRONMENT
              value: "{{ .Values.webistecs.environment.aspNetCoreEnvironment }}"
            - name: COINBASE__PRIVATEKEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.webistecs.secrets.webistecsSecret }}
                  key: {{ .Values.webistecs.secrets.coinbase__privateKey }}
            - name: COINBASE__PRIVATEKEYNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.webistecs.secrets.webistecsSecret }}
                  key: {{ .Values.webistecs.secrets.coinbase__privateName }}
            - name: ConnectionStrings__WebistecsContext
              value: "{{ .Values.webistecs.environment.webistecsContext }}"
            - name: GRAFANA_URL
              value: "http://192.168.68.107:32100"
            - name: LOKI_URL
              value: "https://log-api.eu.newrelic.com/log/v1"
            - name: NEWRELIC__APIKEY
              valueFrom:
                secretKeyRef:
                  name: webistecs-secret
                  key: NEWRELIC__APIKEY
            - name: TELEGRAM__NOTIFICATIONS
              valueFrom:
                secretKeyRef:
                  name: webistecs-secret
                  key: TELEGRAM__NOTIFICATIONS
            - name: TELEGRAM__ERRORS
              valueFrom:
                secretKeyRef:
                  name: webistecs-secret
                  key: TELEGRAM__ERRORS
            - name: TELEGRAM__FUNCTIONS
              valueFrom:
                secretKeyRef:
                  name: webistecs-secret
                  key: TELEGRAM__FUNCTIONS
            - name: TELEGRAM__LISTENER_ID
              valueFrom:
                secretKeyRef:
                  name: webistecs-secret
                  key: TELEGRAM__LISTENER_ID
            - name: TELEGRAM__API_HASH
              valueFrom:
                secretKeyRef:
                  name: webistecs-secret
                  key: TELEGRAM__API_HASH
            - name: TELEGRAM__FUNCTIONS_HASH
              valueFrom:
                secretKeyRef:
                  name: webistecs-secret
                  key: TELEGRAM__FUNCTIONS_HASH
            - name: TELEGRAM__PHONE_NUMBER
              valueFrom:
                secretKeyRef:
                  name: webistecs-secret
                  key: TELEGRAM__PHONE_NUMBER
            - name: TELEGRAM__RELEASES
              valueFrom:
                secretKeyRef:
                  name: webistecs-secret
                  key: TELEGRAM__RELEASES  

            - name: TELEGRAM_CHANNELS
              value: '[
                  {"Type": "Notifications", "Id": "$(TELEGRAM__NOTIFICATIONS)"},
                  {"Type": "Errors", "Id": "$(TELEGRAM__ERRORS)"},
                  {"Type": "Functions", "Id": "$(TELEGRAM__FUNCTIONS)"},
                  {"Type": "Releases", "Id": "$(TELEGRAM__RELEASES)"}
              ]'

            - name: TELEGRAM_LISTENER
              value: '{
                  "Id": "$(TELEGRAM__LISTENER_ID)",
                  "Hash": "$(TELEGRAM__API_HASH)",
                  "PhoneNumber": "$(TELEGRAM__PHONE_NUMBER)"
              }'      
            
          resources:
            requests:
              memory: "{{ .Values.webistecs.resources.requests.memory }}"
              cpu: "{{ .Values.webistecs.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.webistecs.resources.limits.memory }}"
              cpu: "{{ .Values.webistecs.resources.limits.cpu }}"
          volumeMounts:
            - name: db-volume
              mountPath: {{ .Values.webistecs.volumeMountPath }}
        - name: {{ .Values.nodeExporter.name }}
          image: "{{ .Values.nodeExporter.image }}"
          ports:
            - containerPort: {{ .Values.nodeExporter.containerPort }}
      restartPolicy: {{ .Values.webistecs.restartPolicy }}
      imagePullSecrets:
        - name: {{ .Values.webistecs.imagePullSecret }}
      volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName: {{ .Values.webistecs.volume.persistentVolumeClaim.claimName }}