apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webistecs.fullname" . }}-test
  annotations:
    checksum/config: "{{ printf "%s:%s" .Values.webistecs.image.repository .Values.webistecs.image.tag | sha256sum }}"
spec:
  replicas: {{ .Values.webistecs.replicaCount }}
  selector:
    matchLabels:
      {{- include "webistecs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "webistecs.selectorLabels" . | nindent 8 }}
      annotations:
        co.elastic.logs/enabled: {{ .Values.webistecs.logging.enabled | quote }}
        co.elastic.logs/module: {{ .Values.webistecs.logging.module | quote }}
        co.elastic.logs/fileset.stdout: {{ .Values.webistecs.logging.fileset.stdout | quote }}
        co.elastic.logs/fileset.stderr: {{ .Values.webistecs.logging.fileset.stderr | quote }}
        checksum/config: "{{ printf "%s:%s" .Values.webistecs.image.repository .Values.webistecs.image.tag | sha256sum }}"
    spec:
      containers:
        - name: {{ .Values.webistecs.containerName }}
          image: "{{ .Values.webistecs.image.repository }}:{{ .Values.webistecs.image.tag }}"
          imagePullPolicy: {{ .Values.webistecs.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.webistecs.containerPort }}
          readinessProbe:
            httpGet:
              path: {{ .Values.webistecs.readinessProbe.path }}
              port: {{ .Values.webistecs.readinessProbe.port }}
            initialDelaySeconds: {{ .Values.webistecs.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.webistecs.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.webistecs.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.webistecs.readinessProbe.successThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .Values.webistecs.livenessProbe.path }}
              port: {{ .Values.webistecs.livenessProbe.port }}
            initialDelaySeconds: {{ .Values.webistecs.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.webistecs.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.webistecs.livenessProbe.failureThreshold }}
          env:
            - name: APPLICATION__EnvironmentType
              value: "Development"
            - name: environmentVariables__ASPNETCORE__ENVIRONMENT
              value: "Development"
            - name: environmentVariables__ASPNETCORE_TYPE
              value: "Development"
            - name: environmentVariables__ASPNETCORE__TYPE
              value: "Development"
            - name: ASPNETCORE__ENVIRONMENT
              value: "{{ .Values.webistecs.environment.aspNetCoreEnvironment }}"
            - name: COINBASE__PRIVATEKEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.webistecs.secrets.webistecsSecret }}
                  key: coinbase__privateKey
            - name: COINBASE__PRIVATEKEYNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.webistecs.secrets.webistecsSecret }}
                  key: coinbase__privateName
            - name: ConnectionStrings__WebistecsContext
              value: "{{ .Values.webistecs.environment.webistecsContext }}"
            - name: GRAFANA__URL
              value: "http://192.168.68.107:32100"
            - name: LOKI__URL
              value: "https://log-api.eu.newrelic.com/log/v1"
            - name: NEWRELIC__APIKEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.webistecs.secrets.webistecsSecret }}
                  key: NEWRELIC__APIKEY

            # Telegram Configuration
            - name: Telegram__Token
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.webistecs.secrets.webistecsSecret }}
                  key: TELEGRAM__TOKEN
            - name: Telegram__Channels__0__Type
              value: "Notifications"
            - name: Telegram__Channels__0__Id
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.webistecs.secrets.webistecsSecret }}
                  key: TELEGRAM__NOTIFICATIONS
            - name: Telegram__Channels__1__Type
              value: "Errors"
            - name: Telegram__Channels__1__Id
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.webistecs.secrets.webistecsSecret }}
                  key: TELEGRAM__ERRORS
            - name: Telegram__Channels__2__Type
              value: "Functions"
            - name: Telegram__Channels__2__Id
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.webistecs.secrets.webistecsSecret }}
                  key: TELEGRAM__FUNCTIONS
            - name: Telegram__Listener__Id
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.webistecs.secrets.webistecsSecret }}
                  key: TELEGRAM__LISTENER_ID
            - name: Telegram__Listener__Hash
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.webistecs.secrets.webistecsSecret }}
                  key: TELEGRAM__API_HASH
            - name: Telegram__Listener__PhoneNumber
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.webistecs.secrets.webistecsSecret }}
                  key: TELEGRAM__PHONE_NUMBER

          resources:
            requests:
              memory: "{{ .Values.webistecs.resources.requests.memory }}"
              cpu: "{{ .Values.webistecs.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.webistecs.resources.limits.memory }}"
              cpu: "{{ .Values.webistecs.resources.limits.cpu }}"
          volumeMounts:
            - name: db-volume
              mountPath: {{ .Values.webistecs.volumeMountPath }}
        - name: {{ .Values.nodeExporter.name }}
          image: "{{ .Values.nodeExporter.image }}"
          ports:
            - containerPort: {{ .Values.nodeExporter.containerPort }}
      restartPolicy: {{ .Values.webistecs.restartPolicy }}
      imagePullSecrets:
        - name: {{ .Values.webistecs.imagePullSecret }}
      volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName: {{ .Values.webistecs.volume.persistentVolumeClaim.claimName }}