postgres:
  database: webistecs  
  user: myappuser      
  password: mypassword 
  env:
    - name: PGDATA
      value: /pgdata
    - name: POSTGRES_INITDB_ARGS
      value: "--auth-host=scram-sha-256"
    - name: POSTGRES_HOST_AUTH_METHOD
      value: "scram-sha-256"

service:
  nodePort: 30034 