image:
  repository: postgres
  tag: "15"
  pullPolicy: IfNotPresent

postgres:
  user: myappuser
  password: mypassword
  database: webistecs
  env:
    - name: PGDATA
      value: /pgdata

    - name: POSTGRES_INITDB_ARGS
      value: "--auth-host=scram-sha-256 --no-postgres-role"
    - name: POSTGRES_HOST_AUTH_METHOD
      value: "scram-sha-256"

service:
  type: NodePort
  port: 5432
  nodePort: 30034  

persistence:
  enabled: true
  size: 5Gi
  storageClass: longhorn  

resources: {}  