postgres:
  database: webistecs-test
  user: myappuser
  password: mypassword  # Warning: Hardcoded credentials (use secrets in production)
  env:
    - name: PGDATA
      value: /pgdata
    - name: POSTGRES_INITDB_ARGS
      value: "--auth-host=scram-sha-256"
    - name: POSTGRES_HOST_AUTH_METHOD
      value: "scram-sha-256"

image:
  repository: postgres
  tag: "15"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: NodePort
  port: 5432
  nodePort: 30033  # Hardcoded NodePort (ensure it's unused in your cluster)

persistence:
  enabled: true
  size: 5Gi
  storageClass: longhorn  # Ensure this StorageClass exists