replicaCount: 1

image:
  repository: postgres
  tag: "15"
  pullPolicy: IfNotPresent

postgres:
  user: myappuser
  password: mypassword
  database: webistecs  # <-- PROD DB NAME
  env:
    - name: PGDATA
      value: /var/lib/postgresql/data/pgdata

service:
  type: NodePort
  port: 5432
  nodePort: 30034  # Prod NodePort (different from test)

persistence:
  enabled: true
  size: 5Gi
  storageClass: longhorn

resources: {}

volumeMounts:
  - name: postgres-storage
    mountPath: /var/lib/postgresql/data/pgdata
