replicaCount: 1

image:
  repository: postgres
  tag: "15"
  pullPolicy: IfNotPresent

postgres:
  user: myappuser
  password: mypassword
  database: webistecs

service:
  type: NodePort
  port: 5432
  nodePort: 30034  # <- Chose a static NodePort (Different from test)

persistence:
  enabled: true
  size: 5Gi
  storageClass: ""

resources: {}

fullnameOverride: postgresql-prod
