replicaCount: 1

image:
  repository: postgres
  tag: "15"
  pullPolicy: IfNotPresent

postgres:
  user: myappuser
  password: mypassword
  database: webistecs  # change to webistecs-test for test env
  env:
    - name: PGDATA
      value: /pgdata

service:
  type: NodePort
  port: 5432
  nodePort: 30034  # adjust for test (e.g., 30033)

persistence:
  enabled: true
  size: 5Gi
  storageClass: longhorn

resources: {}

volumeMounts:
  - name: postgres-storage
    mountPath: /pgdata