postgresqlInstances:
  prod:
    replicaCount: 1
    image:
      repository: postgres
      tag: "15"
      pullPolicy: IfNotPresent
    postgres:
      user: myappuser
      password: mypassword
      database: webistecs
      pgdata: /pgdata
      additionalEnv: {}
    service:
      type: ClusterIP
      port: 5432
  test:
    replicaCount: 1
    image:
      repository: postgres
      tag: "15"
      pullPolicy: IfNotPresent
    postgres:
      user: myappuser
      password: mypassword
      database: webistecs
      pgdata: /pgdata
      additionalEnv: {}
    service:
      type: ClusterIP
      port: 5432
  staging:
    replicaCount: 1
    image:
      repository: postgres
      tag: "15"
      pullPolicy: IfNotPresent
    postgres:
      user: myappuser
      password: mypassword
      database: webistecs
      pgdata: /pgdata
      additionalEnv: {}
    service:
      type: ClusterIP
      port: 5432
