replicaCount: 1

image:
  repository: postgres
  tag: "15"
  pullPolicy: IfNotPresent

postgres:
  user: myappuser
  password: mypassword
  database: webistecs

service:
  type: ClusterIP
  port: 5432

persistence:
  enabled: true
  size: 5Gi
  storageClass: ""

resources: {}