server:
  service:
    type: NodePort
    nodePortHttp: 30007  # HTTP UI & API
    nodePortHttps: 30008 # Optional SSL

configs:
  params:
    server.insecure: true

rbac:
  policy.csv: |
    p, role:admin, *, *, *, allow
    g, user:admin, role:admin
  policy.default: role:admin
  policy.matchMode: glob
  scopes: '[username]'
