server:
  service:
    type: LoadBalancer
    ports:
      http: 80
configs:
  params:
    server.insecure: true  # If you're only serving over HTTP

rbac:
  policy.csv: |
    p, role:admin, *, *, *, allow
    g, user:admin, role:admin
  policy.default: role:admin
  policy.matchMode: glob
  scopes: '[username]'
