server:
  service:
    type: NodePort
    ports:
      http: 80

configs:
  params:
    server.insecure: true  

rbac:
  policy.csv: |
    p, role:admin, *, *, *, allow
    g, user:admin, role:admin
  policy.default: role:admin
  policy.matchMode: glob
  scopes: '[username]'
