apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-shared-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: local-path   
  hostPath:
    path: /webistecs-storage/database
    type: DirectoryOrCreate
