apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-shared-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: postgres-shared-pv
  storageClassName: local-path   
