server:
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  service:
    type: NodePort
    # HTTP configuration:
    servicePortHttp: 80         # The port that the service exposes inside the cluster for HTTP
    targetPort: 8080            # The container port to which the service forwards traffic
    nodePortHttp: 30007         # The NodePort for HTTP traffic (your desired port)
    # Optionally, if you need HTTPS, you can configure these:
    servicePortHttps: 443       # The service's HTTPS port inside the cluster
    nodePortHttps: 30443        # The NodePort for HTTPS traffic

controller:
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

repoServer:
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi

dex:
  enabled: false
