apiVersion: v1
kind: Secret
metadata:
  name: argocd-image-updater-secret
  namespace: argocd
stringData:
  argocd.token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJhZG1pbjphcGlLZXkiLCJuYmYiOjE3NDEyNTIxMzAsImlhdCI6MTc0MTI1MjEzMCwianRpIjoiYXJnb2NkLWltYWdlLXVwZGF0ZXItdG9rZW4ifQ.XhcDXCMIXW2EohJIzjgPOUxK5Xzadhiq2iSpYL_Ovk4"
