apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-image-updater
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-image-updater
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-image-updater
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-image-updater
    spec:
      serviceAccountName: argocd-image-updater
      containers:
        - name: argocd-image-updater
          image: quay.io/argoprojlabs/argocd-image-updater:v0.12.0
          args:
            - "run"  # ✅ Use "run" instead of invalid flags
            - "--loglevel=info"
          env:
            - name: ARGOCD_SERVER
              value: "argocd-server.argocd.svc:443"
            - name: ARGOCD_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: argocd-image-updater
                  key: argocd.token
          volumeMounts:
            - mountPath: /app/config
              name: argocd-image-updater-config
      volumes:
        - name: argocd-image-updater-config
          configMap:
            name: argocd-image-updater-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  git_write_back: "true"  #
  git_commit_user: "ArgoCD Image Updater"
  git_commit_email: "argocd@enumandco@gmail.com"
  git_branch: "main"
