apiVersion: v1
kind: PersistentVolume
metadata:
  name: backtest-results-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  volumeMode: Filesystem
  hostPath:
    path: /mnt/data/backtest-results
