apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backtest-results-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany  # Match the PV access mode
  resources:
    requests:
      storage: 1Gi  # Match the PV capacity
  volumeName: backtest-results-pv  # Explicitly reference the available PV
