apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: monitoring
  labels:
    app: elasticsearch
spec:
  type: NodePort
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
      name: http
      nodePort: 32000
    - port: 9300
      targetPort: 9300
      protocol: TCP
      name: transport
      nodePort: 32001
  selector:
    app: elasticsearch
