apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
    component: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
      component: ui
  template:
    metadata:
      labels:
        app: grafana
        component: ui
    spec:
      containers:
        - name: grafana
          image: "grafana/grafana-enterprise:11.0.0"
          securityContext:
            runAsUser: 472
          env:
            - name: GF_AUTH_DISABLE_LOGIN_FORM
              value: "false"
            - name: GF_LOG_LEVEL
              value: "info"
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          volumeMounts:
            - name: grafana-data
              mountPath: "/var/lib/grafana"
      volumes:
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-nfs-claim
