apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-nfs-volume
  labels:
    app: grafana
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    path: /mnt/nfsshare/grafana
    server: 192.168.68.107
