apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-test-postgresql-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi  # Adjust this size if needed
  storageClassName: local-storage
