apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pricedata-test-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi
  volumeName: pricedata-test-pv
