apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
  labels:
    mylabel: prometheus-configmap
data:
  prometheus.yml: |
    global:
      scrape_interval: 1m

    scrape_configs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        metric_relabel_configs:

      - job_name: 'kube-state-metrics'
        kubernetes_sd_configs:
          - role: service
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name]
            action: keep
            regex: kube-system;kube-state-metrics

      - job_name: 'coinmarketcap-exporter'
        static_configs:
          - targets: ['192.168.68.107:32005']

      - job_name: 'websitecs'
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_mylabel]
            target_label: websitecs
        static_configs:
          - targets: ['192.168.68.107:30080']

      - job_name: 'node-exporter'
        static_configs:
          - targets: ['192.168.68.107:9100']