apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-nfs-claim
  namespace: monitoring
spec:
  selector:
    matchLabels:
      type: prometheus
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
