apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-nfs-volume
  namespace: monitoring
  labels:
    type: prometheus
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    path: /mnt/nfsshare/prometheus
    server: 192.168.68.107
