---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backtest-results-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  volumeMode: Filesystem
  hostPath:
    path: /mnt/data/backtest-results
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backtest-results-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: backtest-results-pv
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pricedata-local-pv
  labels:
    type: pricedata
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /Users/emabhiza/Dev/webistecs-storage/pricedata
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3d-k3s-server-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pricedata-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi
  volumeName: pricedata-local-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pricedata-test-pv
  labels:
    type: pricedata-test
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /Users/emabhiza/Dev/webistecs-storage/pricedata
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3d-k3s-server-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pricedata-test-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi
  volumeName: pricedata-test-pv
