apiVersion: batch/v1
kind: CronJob
metadata:
  name: webistecs-monitor-cronjob
  namespace: default
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: webistecs-util
              image: emabhiza/webistecs-util:finale-71
              imagePullPolicy: Always
              env:
                - name: ASPNETCORE_ENVIRONMENT
                  value: "Production"
                - name: LOCAL_BACKUP_PATH
                  value: "/home/emabhiza/webistecs-backup"
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: "/secrets/webistecs_backCredentials.json"
                - name: HEALTH_CHECK_URL
                  value: "http://192.168.68.107:30080/healthz"
                - name: CLIENT_EMAIL
                  value: "webistecs@webistecs.iam.gserviceaccount.com"
                - name: DB_PATH
                  value: "/mnt/source/webistecs-database/webistecs.db"
                - name: BACKUP_PATH
                  value: "/home/emabhiza/webistecs-backup"
              volumeMounts:
                - name: source-storage
                  mountPath: /mnt/source
                - name: db-storage
                  mountPath: /mnt/source/webistecs-database
                - name: backup-storage
                  mountPath: /home/emabhiza/webistecs-backup
                - name: google-credentials
                  mountPath: /secrets
                  readOnly: true
          restartPolicy: OnFailure
          volumes:
            - name: source-storage
              hostPath:
                path: /media/emabhiza/webistecsStorage/webistecs
                type: Directory
            - name: db-storage
              hostPath:
                path: /media/emabhiza/webistecsStorage/webistecs/database
                type: Directory
            - name: backup-storage
              hostPath:
                path: /home/emabhiza/webistecs-backup
                type: Directory
            - name: google-credentials
              secret:
                secretName: webistecs-secret
