apiVersion: v1
kind: PersistentVolume
metadata:
  name: webistecs-local-pv
  labels:
    type: webistecs
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /media/emabhiza/webistecsStorage/webistecs/database
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - raspberrypi