apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webistecs-session-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
