apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: backtester-template
  namespace: default
spec:
  entrypoint: backtest-job
  volumes:
    - name: pricedata-volume
      persistentVolumeClaim:
        claimName: pricedata-test-pvc
    - name: result-volume
      persistentVolumeClaim:
        claimName: backtest-results-pvc

  arguments:
    parameters:
      - name: year
      - name: month
      - name: initialUsdc
      - name: strategy
      - name: Combo_Upper_Start
      - name: Combo_Upper_EndValue
      - name: Combo_Upper_Target
      - name: Combo_Upper_Weight
      - name: Combo_Middle_Start
      - name: Combo_Middle_EndValue
      - name: Combo_Middle_Target
      - name: Combo_Middle_Weight
      - name: Combo_Lower_Start
      - name: Combo_Lower_EndValue
      - name: Combo_Lower_Target
      - name: Combo_Lower_Weight

  templates:
    - name: backtest-job
      inputs:
        parameters:
          - name: year
          - name: month
          - name: initialUsdc
          - name: strategy
          - name: Combo_Upper_Start
          - name: Combo_Upper_EndValue
          - name: Combo_Upper_Target
          - name: Combo_Upper_Weight
          - name: Combo_Middle_Start
          - name: Combo_Middle_EndValue
          - name: Combo_Middle_Target
          - name: Combo_Middle_Weight
          - name: Combo_Lower_Start
          - name: Combo_Lower_EndValue
          - name: Combo_Lower_Target
          - name: Combo_Lower_Weight

      container:
        image: emabhiza/webistecs-backtest:test-0.0.2
        workingDir: /app
        command: ["sh", "-c"]
        args:
          - |
            echo "Mounted Data:"
            ls -lh /app/Resources

            echo "Environment Vars:"
            printenv | grep BacktestParameters || true

            echo "Running .NET Info..."
            dotnet --info

            echo "=== Running Backtester ==="
            dotnet Backtester.dll

            echo "=== Printing Backtester Logs ==="
            if ls /app/backtest-results/*.log 1> /dev/null 2>&1; then
              cat /app/backtest-results/*.log
            else
              echo "No log files found in /app/backtest-results/"
            fi

            echo "Sleeping for debug (even on success)..."
            sleep 300
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: DATA_DIR
            value: /app/Resources
          - name: RESULTS_DIR
            value: /app/backtest-results
          - name: BacktestParameters__Year
            value: "{{inputs.parameters.year}}"
          - name: BacktestParameters__Month
            value: "{{inputs.parameters.month}}"
          - name: BacktestParameters__InitialUsdc
            value: "{{inputs.parameters.initialUsdc}}"
          - name: BacktestParameters__Strategy
            value: "{{inputs.parameters.strategy}}"
          - name: BacktestParameters__Combo_Upper_Start
            value: "{{inputs.parameters.Combo_Upper_Start}}"
          - name: BacktestParameters__Combo_Upper_EndValue
            value: "{{inputs.parameters.Combo_Upper_EndValue}}"
          - name: BacktestParameters__Combo_Upper_Target
            value: "{{inputs.parameters.Combo_Upper_Target}}"
          - name: BacktestParameters__Combo_Upper_Weight
            value: "{{inputs.parameters.Combo_Upper_Weight}}"
          - name: BacktestParameters__Combo_Middle_Start
            value: "{{inputs.parameters.Combo_Middle_Start}}"
          - name: BacktestParameters__Combo_Middle_EndValue
            value: "{{inputs.parameters.Combo_Middle_EndValue}}"
          - name: BacktestParameters__Combo_Middle_Target
            value: "{{inputs.parameters.Combo_Middle_Target}}"
          - name: BacktestParameters__Combo_Middle_Weight
            value: "{{inputs.parameters.Combo_Middle_Weight}}"
          - name: BacktestParameters__Combo_Lower_Start
            value: "{{inputs.parameters.Combo_Lower_Start}}"
          - name: BacktestParameters__Combo_Lower_EndValue
            value: "{{inputs.parameters.Combo_Lower_EndValue}}"
          - name: BacktestParameters__Combo_Lower_Target
            value: "{{inputs.parameters.Combo_Lower_Target}}"
          - name: BacktestParameters__Combo_Lower_Weight
            value: "{{inputs.parameters.Combo_Lower_Weight}}"
        volumeMounts:
          - name: pricedata-volume
            mountPath: /app/Resources
            readOnly: true
          - name: result-volume
            mountPath: /app/backtest-results

      outputs:
        artifacts:
          - name: backtest-results
            path: /app/backtest-results
            optional: true