apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: backtester-jobs
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/emabhiza/webistecs-charts.git
        revision: backtest
        files:
          - path: scripts/generated-combos/combo-*.yaml
  template:
    metadata:
      name: "backtester-{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/emabhiza/webistecs-charts.git
        targetRevision: backtest
        path: webistecs
        helm:
          values: |
            backtester:
              comboId: {{path.basename | regexReplaceAll "combo-|\\.yaml" ""}}
              {{ readFile (print "scripts/generated-combos/" path.basename) | nindent 14 }}
          valueFiles:
            - values-backtester.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: default
