apiVersion: v1
kind: Pod
metadata:
  name: debug-dummy
  namespace: default
spec:
  containers:
    - name: debug
      image: alpine
      command: [ "sleep", "3600" ]
      volumeMounts:
        - name: pricedata-volume
          mountPath: /app/pricedata
  volumes:
    - name: pricedata-volume
      persistentVolumeClaim:
        claimName: pricedata-test-pvc
  restartPolicy: Never
