apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/emabhiza/webistecs-charts.git'
    targetRevision: backtest
    path: postgresql
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
