apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared-storage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/emabhiza/webistecs-charts.git'
    targetRevision: main
    path: storage      
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
