apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webistecs
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: webistecs=emabhiza/webistecs
    argocd-image-updater.argoproj.io/webistecs.image-name: image.repository
    argocd-image-updater.argoproj.io/webistecs.update-strategy: semver
    argocd-image-updater.argoproj.io/webistecs.allow-tags: regexp:^v\d+\.\d+\.\d+$
    argocd-image-updater.argoproj.io/webistecs.force-update: "true"
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/emabhiza/webistecs-charts.git'
    targetRevision: main
    path: webistecs
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
