apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webistecs
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: "docker.io/emabhiza/webistecs"
    argocd-image-updater.argoproj.io/update-strategy: newest-build
    argocd-image-updater.argoproj.io/helm-image-path: webistecs.image
    argocd-image-updater.argoproj.io/image.pull-secret: myregistrykey

spec:
  project: default
  source:
    repoURL: https://github.com/emabhiza/webistecs-charts.git
    targetRevision: main
    path: webistecs
    helm:
      valueFiles:
        - values.yaml
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
