apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webistecs
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/emabhiza/webistecs-charts.git'
    targetRevision: test-env
    path: webistecs
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true