apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webistecs-backtester
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/emabhiza/webistecs-charts.git'
    targetRevision: HEAD
    path: webistecs
    helm:
      valueFiles:
        - values-backtester.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
