apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webistecs-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/emabhiza/webistecs-charts.git'
    path: webistecs
    targetRevision: main
    helm:
      valueFiles:
        - values-test.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true