apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: logging
  labels:
    k8s-app: fluent-bit
spec:
  selector:
    matchLabels:
      k8s-app: fluent-bit
  template:
    metadata:
      labels:
        k8s-app: fluent-bit
    spec:
      serviceAccountName: fluent-bit
      containers:
        - name: fluent-bit
          image: fluent/fluent-bit:3.2.8-arm64
          imagePullPolicy: Always
          env:
            - name: NEW_RELIC_API_KEY
              value: "eu01xx0cd849adbef3fcaa64c4cafc3bFFFFNRAL"
            - name: MALLOC_CONF
              value: "abort_conf:true,background_thread:false"
          ports:
            - containerPort: 2020
          resources:
            limits:
              memory: "300Mi"
              cpu: "150m"
            requests:
              memory: "150Mi"
              cpu: "75m"
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: config-volume
              mountPath: /fluent-bit/etc/
            - name: parsers-volume
              mountPath: /fluent-bit/etc/parsers.conf
              subPath: parsers.conf  # Fix: Mount parsers.conf as a file
            - name: api-secret
              mountPath: /fluent-bit/secrets
              readOnly: true
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: config-volume
          configMap:
            name: fluent-bit-config
        - name: parsers-volume
          configMap:
            name: fluent-bit-config
