apiVersion: v1
kind: Service
metadata:
  name: fluent-bit
  namespace: logging
spec:
  selector:
    k8s-app: fluent-bit
  type: NodePort
  ports:
    - protocol: TCP
      port: 2020
      targetPort: 2020
      nodePort: 30005