apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         5
        Daemon        Off
        Log_Level     info
        Parsers_File  /fluent-bit/etc/parsers.conf  # ✅ Reference parsers file here
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    [INPUT]
        Name          tail
        Path          /var/log/containers/*.log
        Tag           kube.*
        Refresh_Interval  10
        Buffer_Chunk_Size 32k
        Buffer_Max_Size   64k

    [FILTER]
        Name          kubernetes
        Match         kube.*
        Merge_Log     On
        Keep_Log      Off
        Kube_URL      https://kubernetes.default.svc
        K8S-Logging.Parser  On
        K8S-Logging.Include  labels.app.kubernetes.io/name:webistecs

    [FILTER]
        Name          nest
        Match         kube.*
        Operation     lift
        Nested_under  log
        Add_prefix    extracted_

    [FILTER]
        Name          parser
        Match         kube.*
        Key_Name      extracted_message
        Parser        structured_log_parser  # ✅ This parser is now in parsers.conf

  parsers.conf: |
    [PARSER]
        Name        structured_log_parser
        Format      json
        Time_Key    timestamp
        Time_Format %Y-%m-%dT%H:%M:%S

    [MULTILINE]
        Name          multiline_log_parser
        Type          regex
        Flush_Timeout 10
        Rule          "start_state"  "^\S.*(Exception|Error|Trace):|^\d{4}-\d{2}-\d{2}T.* (INF|ERR|WRN|FTL)"  "cont"
        Rule          "cont"         "^\s+at\s|\s+---\s"  "cont"
