apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         5
        Daemon        Off
        Log_Level     debug
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    [INPUT]
        Name          tail
        Path          /var/log/containers/*.log
        Tag           kube.*
        Refresh_Interval  10
        Buffer_Chunk_Size 32k
        Buffer_Max_Size   64k

    [FILTER]
        Name          kubernetes
        Match         kube.*
        Merge_Log     On
        Keep_Log      On  
        Kube_URL      https://kubernetes.default.svc
        K8S-Logging.Parser  On
        Labels        On
        Annotations   Off

    [FILTER]
        Name          grep
        Match         kube.*
        Regex         kubernetes.pod_name ^webistecs.*

    [OUTPUT]
        Name          http
        Match         kube.*
        Host          log-api.eu.newrelic.com
        Port          443
        URI           /log/v1
        Format        json
        tls           on
        Header        Content-Type application/json
        Header        Authorization Bearer eu01xxb8b6f9cde620bd5171843435eaFFFFNRAL