apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         5
        Daemon        Off
        Log_Level     info
        Parsers_File  /fluent-bit/etc/parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    [INPUT]
        Name          tail
        Path          /var/log/containers/*.log
        Tag           kube.*
        Refresh_Interval  10
        Buffer_Chunk_Size 32k
        Buffer_Max_Size   64k

    # Ensure logs are enriched with Kubernetes labels
    [FILTER]
        Name          kubernetes
        Match         kube.*
        Merge_Log     On
        Keep_Log      On  
        Kube_URL      https://kubernetes.default.svc
        K8S-Logging.Parser  On
        Labels        On
        Annotations   Off

    # ✅ STRICT FILTER: Only keep logs from webistecs
    [FILTER]
        Name          grep
        Match         kube.*
        Regex         kubernetes.labels.app.kubernetes.io/name webistecs  # ✅ Correct format

    # If filtering still doesn't work, try filtering by pod name (Alternative)
    # [FILTER]
    #     Name          grep
    #     Match         kube.*
    #     Regex         kubernetes.pod_name webistecs-.*

    [OUTPUT]
        Name          http
        Match         kube.*
        Host          log-api.eu.newrelic.com
        Port          443
        URI           /log/v1
        Format        json
        tls           on
        Header        Content-Type application/json
        Header        Authorization Bearer eu01xxb8b6f9cde620bd5171843435eaFFFFNRAL

  parsers.conf: |
    [PARSER]
        Name        custom_json_parser
        Format      regex
        Regex       ^\[(?<timestamp>[^\]]+)\] \[(?<log_level>[A-Z]+)\] \[(?<source>[^\]]+)\] (?<message>.*)$
        Time_Key    timestamp
        Time_Format %H:%M:%S

    [PARSER]
        Name        structured_log_parser
        Format      json
        Time_Key    timestamp
        Time_Format %Y-%m-%dT%H:%M:%S

    [MULTILINE]
        Name          multiline_log_parser
        Type          regex
        Flush_Timeout 10
        Rule          "start_state"  "^\S.*(Exception|Error|Trace):|^\d{4}-\d{2}-\d{2}T.* (INF|ERR|WRN|FTL)"  "cont"
        Rule          "cont"         "^\s+at\s|\s+---\s"  "cont"
