apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |
   [ SERVICE ]
    Flush         5
    Daemon        Off
    Log_Level     info
    Parsers_File  /fluent-bit/etc/parsers.conf
  
    [ INPUT ]
    Name          tail
    Path          /var/log/containers/*.log
    Tag           kube.*
    Parser        structured_log_parser
    Refresh_Interval  10
    Buffer_Chunk_Size 32k
    Buffer_Max_Size   64k
  
    [ FILTER ]
    Name          kubernetes
    Match         kube.*
    Merge_Log     On
    Keep_Log      Off
    Kube_URL      https://kubernetes.default.svc
    K8S-Logging.Parser  On
  
    # ✅ Keep only logs from container "webistecs"
    [ FILTER ]
    Name          grep
    Match         kube.*
    Regex         kubernetes.container_name ^webistecs$
  
    [ FILTER ]
    Name          modify
    Match         kube.*
    Rename        @t timestamp
    Rename        @l level
    Rename        @m message
    Rename        @x exception
    Rename        Application application
    Rename        MachineName machine
    Rename        AssetName asset
    Rename        RequestType request_type
    Rename        Response response
  
    [ OUTPUT ]
    Name          stdout
    Match         *