apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         5
        Daemon        Off
        Log_Level     info
        Parsers_File  parsers.conf

    [INPUT]
        Name          tail
        Path          /var/log/containers/*.log
        Parser        docker
        Tag           kube.*

    [OUTPUT]
        Name          http
        Match         *
        Host          log-api.eu.newrelic.com
        Port          443
        URI           /log/v1
        Format        json
        tls           On
        Header        Content-Type application/json
        Header        Authorization Bearer ${NEW_RELIC_API_KEY}


  parsers.conf: |
    [PARSER]
        Name         docker
        Format       json
