apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         5
        Daemon        Off
        Log_Level     info
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    [INPUT]
        Name          tail
        Path          /var/log/containers/*.log
        Tag           kube.*
        Refresh_Interval  10
        Buffer_Chunk_Size 32k
        Buffer_Max_Size   64k

    [FILTER]
        Name          kubernetes
        Match         kube.*
        Merge_Log     On
        Keep_Log      On  
        Kube_URL      https://kubernetes.default.svc
        K8S-Logging.Parser  On
        Labels        On
        Annotations   Off

    [FILTER]
        Name          parser
        Match         kube.*
        Key_Name      log
        Parser        plain_text_parser

    [OUTPUT]
        Name          http
        Match         *
        Host          log-api.eu.newrelic.com
        Port          443
        URI           /log/v1
        Format        json
        tls           on
        Header        Content-Type application/json
        Header        Authorization Bearer eu01xxb8b6f9cde620bd5171843435eaFFFFNRAL

  parsers.conf: |
    [PARSER]
        Name        plain_text_parser
        Format      regex
        Regex       ^(?<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2})\s+(?<log_level>\w+)\s+(?<message>.*)$
        Time_Key    timestamp
        Time_Format %Y-%m-%dT%H:%M:%S

    [MULTILINE]
        Name          multiline_log_parser
        Type          regex
        Flush_Timeout 10
        Rule          "start_state"  "^\S.*(Exception|Error|Trace):|^\d{4}-\d{2}-\d{2}T.* (INF|ERR|WRN|FTL)"  "cont"
        Rule          "cont"         "^\s+at\s|\s+---\s"  "cont"