apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         5
        Daemon        Off
        Log_Level     info
        Parsers_File  /fluent-bit/etc/parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    [INPUT]
        Name          tail
        Path          /var/log/containers/*.log
        Tag           kube.*
        Refresh_Interval  10
        Buffer_Chunk_Size 32k
        Buffer_Max_Size   64k

    # Kubernetes Metadata Enrichment
    [FILTER]
        Name          kubernetes
        Match         kube.*
        Merge_Log     On
        Keep_Log      On  
        Kube_URL      https://kubernetes.default.svc
        K8S-Logging.Parser  On
        Labels        On
        Annotations   Off

    # ✅ STRICT FILTER: Only keep logs from webistecs
    [FILTER]
        Name          grep
        Match         kube.*
        Regex         kubernetes.container_name ^webistecs.*  # ✅ Keep only webistecs logs

    # ✅ Alternative: Use Namespace Filtering
    # [FILTER]
    #     Name          grep
    #     Match         kube.*
    #     Regex         kubernetes.namespace_name webistecs-namespace  # ✅ Only keep logs from this namespace

    # ✅ Exclude Unwanted Services (Alternative)
    # [FILTER]
    #     Name          grep
    #     Match         kube.*
    #     Exclude       kubernetes.labels.app.kubernetes.io/name argocd.*
    #     Exclude       kubernetes.labels.app.kubernetes.io/name loki.*
    #     Exclude       kubernetes.labels.app.kubernetes.io/name traefik.*

    [OUTPUT]
        Name          http
        Match         kube.*
        Host          log-api.eu.newrelic.com
        Port          443
        URI           /log/v1
        Format        json
        tls           on
        Header        Content-Type application/json
        Header        Authorization Bearer eu01xxb8b6f9cde620bd5171843435eaFFFFNRAL
