apiVersion: v1
kind: Service
metadata:
  name: loki-nodeport
  namespace: logging
spec:
  type: NodePort
  selector:
    app: loki
  ports:
    - name: http
      protocol: TCP
      port: 3100      # Loki's internal port
      targetPort: 3100
      nodePort: 32100  # Exposes Loki on this NodePort (between 30000-32767)
