apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.coinmarketcapExporter.name }}
  namespace: {{ .Values.coinmarketcapExporter.namespace }}
  labels:
    app: {{ .Values.coinmarketcapExporter.name }}
spec:
  type: {{ .Values.coinmarketcapExporter.service.type }}
  ports:
    - name: "9101"
      port: {{ .Values.coinmarketcapExporter.containerPort }}
      targetPort: {{ .Values.coinmarketcapExporter.containerPort }}
      nodePort: {{ .Values.coinmarketcapExporter.service.nodePort }}
  selector:
    app: {{ .Values.coinmarketcapExporter.name }}
