apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.coinmarketcapExporter.name }}
  namespace: {{ .Values.coinmarketcapExporter.namespace }}
  labels:
    app: {{ .Values.coinmarketcapExporter.name }}
spec:
  replicas: {{ .Values.coinmarketcapExporter.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.coinmarketcapExporter.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.coinmarketcapExporter.name }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "{{ .Values.coinmarketcapExporter.containerPort }}"
    spec:
      containers:
        - name: {{ .Values.coinmarketcapExporter.name }}
          image: "{{ .Values.coinmarketcapExporter.image.repository }}:{{ .Values.coinmarketcapExporter.image.tag }}"
          ports:
            - containerPort: {{ .Values.coinmarketcapExporter.containerPort }}
          env:
            - name: API_KEY
              value: {{ .Values.coinmarketcapExporter.environment.apiKey }}
            - name: CURRENCY
              value: {{ .Values.coinmarketcapExporter.environment.currency }}
          resources:
            requests:
              memory: "{{ .Values.coinmarketcapExporter.resources.requests.memory }}"
              cpu: "{{ .Values.coinmarketcapExporter.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.coinmarketcapExporter.resources.limits.memory }}"
              cpu: "{{ .Values.coinmarketcapExporter.resources.limits.cpu }}"
      imagePullSecrets:
        - name: {{ .Values.coinmarketcapExporter.imagePullSecrets }}
