apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.webistecs.pv.name }}
  labels:
    type: {{ .Values.webistecs.pv.labels.type }}
spec:
  capacity:
    storage: {{ .Values.webistecs.pv.capacity }}
  accessModes:
    - {{ .Values.webistecs.pv.accessModes }}
  persistentVolumeReclaimPolicy: {{ .Values.webistecs.pv.persistentVolumeReclaimPolicy }}
  storageClassName: {{ .Values.webistecs.pv.storageClassName }}
  nfs:
    path: {{ .Values.webistecs.pv.nfs.path }}
    server: {{ .Values.webistecs.pv.nfs.server }}
