apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.webistecs.pvc.name }}
spec:
  accessModes:
    - {{ .Values.webistecs.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.webistecs.pvc.resources.requests.storage }}
  storageClassName: {{ .Values.webistecs.pvc.storageClassName }}
  selector:
    matchLabels:
      type: {{ .Values.webistecs.pvc.selector.matchLabels.type }}
