apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: default
spec:
  containers:
    - name: debug
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: db-volume
          mountPath: /db
  volumes:
    - name: db-volume
      persistentVolumeClaim:
        claimName: webistecs-db-pvc
  restartPolicy: Never
