apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.elasticsearch.name }}-service
  namespace: {{ .Values.elasticsearch.namespace }}
  labels:
    app: {{ .Values.elasticsearch.name }}
spec:
  type: {{ .Values.elasticsearch.service.type }}
  ports:
    - port: {{ .Values.elasticsearch.ports.http.containerPort }}
      targetPort: {{ .Values.elasticsearch.ports.http.containerPort }}
      protocol: TCP
      name: http
      nodePort: {{ .Values.elasticsearch.ports.http.nodePort }}
    - port: {{ .Values.elasticsearch.ports.transport.containerPort }}
      targetPort: {{ .Values.elasticsearch.ports.transport.containerPort }}
      protocol: TCP
      name: transport
      nodePort: {{ .Values.elasticsearch.ports.transport.nodePort }}
  selector:
    app: {{ .Values.elasticsearch.name }}
