# fluentd-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: logging
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*webistecs*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      format json
      time_key time
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      keep_time_key true
    </source>

    <filter kubernetes.**>
      @type grep
      <regexp>
        key $.kubernetes.labels.app
        pattern ^webistecs$
      </regexp>
    </filter>

    <match kubernetes.**>
      @type copy
      <store>
        @type loki
        url http://loki:3100
        labels {"app": "webistecs"}
      </store>
      <store>
        @type file
        path /var/log/fluentd/webistecs-json.log
        format json
      </store>
      <store>
        @type file
        path /var/log/fluentd-secondary/webistecs-json.log
        format json
      </store>
    </match>