apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
  namespace: monitoring
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Daemon        Off
        Log_Level     info
        Parsers_File  parsers.conf

    [INPUT]
        Name          tail
        Tag           kubernetes.*
        Path          /var/log/containers/*webistecs*.log
        Parser        docker
        DB            /var/log/fluentbit-containers.db
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [FILTER]
        Name          grep
        Match         kubernetes.*
        Regex         kubernetes.labels.app  webistecs

    [OUTPUT]
        Name          loki
        Match         *
        Url           http://loki:3100/loki/api/v1/push
        Labels        {"app":"webistecs"}
        LineFormat    json

    [OUTPUT]
        Name          file
        Match         *
        Path          /var/log/fluentbit/primary
        Format        json_lines

    [OUTPUT]
        Name          file
        Match         *
        Path          /var/log/fluentbit/secondary
        Format        json_lines

  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%NZ
