apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: logging
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
        - name: fluentd
          image: fluent/fluentd-kubernetes-daemonset:v1.16-debian-loki
          env:
            - name: FLUENT_UID
              value: "0"
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: fluentd-config
              mountPath: /fluentd/etc/fluent.conf
              subPath: fluent.conf
            - name: fluentd-logs
              mountPath: /var/log/fluentd
            - name: fluentd-json-secondary
              mountPath: /var/log/fluentd-secondary
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: fluentd-config
          configMap:
            name: fluentd-config
        - name: fluentd-logs
          persistentVolumeClaim:
            claimName: fluentd-logs-pvc
        - name: fluentd-json-secondary
          persistentVolumeClaim:
            claimName: fluentd-json-secondary-pvc