apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.ini: |
    [rendering]
    server_url = https://render.grafana.com
    callback_url = http://192.168.68.107:30091/