apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.grafana.pv.name }}
  labels:
    app: {{ .Values.grafana.labels.app }}
spec:
  capacity:
    storage: {{ .Values.grafana.pv.storage }}
  accessModes:
    - {{ .Values.grafana.pv.accessModes }}
  persistentVolumeReclaimPolicy: {{ .Values.grafana.pv.reclaimPolicy }}
  storageClassName: {{ .Values.grafana.pv.storageClassName }}
  nfs:
    path: {{ .Values.grafana.pv.path }}
    server: {{ .Values.grafana.pv.server }}
