apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-local-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage