apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-local-pvc
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
