apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.grafana.name }}
  namespace: {{ .Values.global.namespace | default "monitoring" }}
  labels:
    app: {{ .Values.grafana.labels.app }}
    component: {{ .Values.grafana.labels.component }}
spec:
  replicas: {{ .Values.grafana.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.grafana.labels.app }}
      component: {{ .Values.grafana.labels.component }}
  template:
    metadata:
      labels:
        app: {{ .Values.grafana.labels.app }}
        component: {{ .Values.grafana.labels.component }}
    spec:
      containers:
        - name: {{ .Values.grafana.name }}
          image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
          securityContext:
            runAsUser: {{ .Values.grafana.securityContext.runAsUser }}
          env:
            - name: GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION
              value: {{ .Values.grafana.env.disableInitialAdminCreation | quote }}
            - name: GF_LOG_LEVEL
              value: {{ .Values.grafana.env.logLevel | quote }}
            - name: GF_SECURITY_DISABLE_LOGIN_FORM
              value: {{ .Values.grafana.env.disableLoginForm | quote }}
            - name: GF_SERVER_ROOT_URL
              value: "http://192.168.68.107:30091/"
            - name: GF_SERVER_HTTP_ADDR
              value: "0.0.0.0"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: "Viewer"
          ports:
            - containerPort: {{ .Values.grafana.ports.containerPort }}
          resources:
            requests:
              memory: "{{ .Values.grafana.resources.requests.memory }}"
              cpu: "{{ .Values.grafana.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.grafana.resources.limits.memory }}"
              cpu: "{{ .Values.grafana.resources.limits.cpu }}"
          volumeMounts:
            - name: grafana-data
              mountPath: "/var/lib/grafana"
            - name: grafana-plugins
              mountPath: "/var/lib/grafana/plugins"
            - name: grafana-config
              mountPath: /etc/grafana/grafana.ini
              subPath: grafana.ini
      volumes:
        - name: grafana-data
          persistentVolumeClaim:
            claimName: {{ .Values.grafana.pvcData.name }}
        - name: grafana-plugins
          persistentVolumeClaim:
            claimName: {{ .Values.grafana.pvcPlugins.name }}
        - name: grafana-config
          configMap:
            name: grafana-config