apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kibana.name }}-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.kibana.labels.app }}
spec:
  type: {{ .Values.kibana.service.type }}
  ports:
    - port: {{ .Values.kibana.ports.containerPort }}
      targetPort: {{ .Values.kibana.ports.containerPort }}
      protocol: TCP
      name: http
      nodePort: {{ .Values.kibana.ports.nodePort }}
  selector:
    app: {{ .Values.kibana.labels.app }}
