apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kibana.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.kibana.labels.app }}
spec:
  replicas: {{ .Values.kibana.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.kibana.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.kibana.labels.app }}
    spec:
      containers:
        - name: {{ .Values.kibana.name }}
          image: "{{ .Values.kibana.image.repository }}:{{ .Values.kibana.image.tag }}"
          env:
            - name: ELASTICSEARCH_HOSTS
              value: {{ .Values.kibana.env.elasticsearchHosts | quote }}
          ports:
            - containerPort: {{ .Values.kibana.ports.containerPort }}
