apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-usb-pv
  labels:
    type: local
spec:
  capacity:
    storage: 983Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /media/eugenemabhiza/76E8-CACF/webistecs/prometheus
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - raspberrypi