apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-usb-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 50Gi