apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: logging
spec:
  type: NodePort
  ports:
    - port: 4317  # OTEL gRPC port
      targetPort: 4317
      nodePort: 30001  # Expose on NodePort 30001 for testing
      protocol: TCP
    - port: 4318 #OTEL http port.
      targetPort: 4318
      nodePort: 30002
      protocol: TCP
  selector:
    app: otel-collector