apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: logging
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    exporters:
      newrelic:
        api_key: "${NEWRELIC_API_KEY}"  # Use environment variable for the API key

    service:
      pipelines:
        logs:
          receivers: [otlp]
          exporters: [newrelic]