apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prometheus.name }}-service
  namespace: {{ .Values.prometheus.namespace }}
  labels:
    app: {{ .Values.prometheus.labels.app }}
    component: {{ .Values.prometheus.labels.component }}
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
    - name: "9090"
      port: {{ .Values.prometheus.ports.containerPort }}
      targetPort: {{ .Values.prometheus.ports.containerPort }}
      nodePort: {{ .Values.prometheus.ports.nodePort }}
  selector:
    app: {{ .Values.prometheus.labels.app }}
    component: {{ .Values.prometheus.labels.component }}
