apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.prometheus.pv.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    type: {{ .Values.prometheus.pv.matchLabels.type }}
spec:
  capacity:
    storage: {{ .Values.prometheus.pv.storage }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.prometheus.pv.accessModes }}
  persistentVolumeReclaimPolicy: {{ .Values.prometheus.pv.reclaimPolicy }}
  storageClassName: {{ .Values.prometheus.pv.storageClassName }}
  nfs:
    path: {{ .Values.prometheus.pv.path }}
    server: {{ .Values.global.raspberryIP }}
