server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push

scrape_configs:
  - job_name: kubernetes-logs
    static_configs:
      - targets: ['localhost']
        labels:
          job: kubernetes-logs
          __path__: /var/log/containers/*.log

    pipeline_stages:
      - drop:
          expression: ".*DEBUG.*"
          source: message

      # Extract pod, namespace, and container from filename
      - regex:
          expression: "^(?P<pod>[a-zA-Z0-9-]+)_(?P<namespace>[a-zA-Z0-9-]+)_(?P<container>[a-zA-Z0-9-]+)(?:-[a-f0-9]+)?\\.log$"
          source: __path__

      - labels:
          pod: '{{ if .pod }}{{ .pod }}{{ else }}unknown{{ end }}'
          namespace: '{{ if .namespace }}{{ .namespace }}{{ else }}default{{ end }}'
          container: '{{ if .container }}{{ .container }}{{ else }}unknown{{ end }}'

      # Multi-line handling for logs with stack traces
      - multiline:
          firstline: '^\['
          max_wait_time: 5s
          continue_through: '^(?!\[)'  # Capture stack traces properly

      # Extract time, level, and message
      - regex:
          expression: '^\[(?P<time>\d{2}:\d{2}:\d{2}\.\d{3}) (?P<level>\w{3})\] \[(?P<component>[^\]]+)\] (?P<msg>.+)$'
          source: message

      - labels:
          level: '{{ .level }}'
          component: '{{ .component }}'

      - timestamp:
          source: time
          format: "15:04:05.000"
          location: UTC
          action: replace

      # Extract HTTP status codes
      - regex:
          expression: '.*http request (?:success|failure) (?P<http_status>\d{3}).*'
          source: msg

      - labels:
          http_status: '{{ if .http_status }}{{ .http_status }}{{ else }}unknown{{ end }}'

      # Capture exceptions/errors
      - regex:
          expression: '^(?P<exception>.*(Exception|Error).*)$'
          source: msg
          target: exception_info

      - labels:
          exception: '{{ if .exception_info }}{{ if .exception_info.exception }}true{{ else }}false{{ end }}{{ else }}false{{ end }}'

      # Improve output formatting
      - output:
          source: "[{{ .time }} {{ .level }}] [{{ .component }}] {{ .msg }}"
