apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "monitoringChart.fullname" . }}-node-exporter
  labels:
    {{- include "monitoringChart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.prometheusNodeExporter.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "monitoringChart.name" . }}-node-exporter
  template:
    metadata:
      labels:
        app: {{ include "monitoringChart.name" . }}-node-exporter
    spec:
      containers:
        - name: node-exporter
          image: "{{ .Values.prometheusNodeExporter.image.repository }}:{{ .Values.prometheusNodeExporter.image.tag }}"
          imagePullPolicy: {{ .Values.prometheusNodeExporter.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.prometheusNodeExporter.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.prometheusNodeExporter.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitoringChart.fullname" . }}-node-exporter
  labels:
    {{- include "monitoringChart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.prometheusNodeExporter.service.type }}
  ports:
    - port: {{ .Values.prometheusNodeExporter.service.port }}
      targetPort: {{ .Values.prometheusNodeExporter.service.targetPort }}
  selector:
    app: {{ include "monitoringChart.name" . }}-node-exporter
