apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prometheus.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.prometheus.labels.app }}
    component: {{ .Values.prometheus.labels.component }}
spec:
  replicas: {{ .Values.prometheus.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.prometheus.labels.app }}
      component: {{ .Values.prometheus.labels.component }}
  template:
    metadata:
      labels:
        app: {{ .Values.prometheus.labels.app }}
        component: {{ .Values.prometheus.labels.component }}
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3d-k3s-server-0
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
      initContainers:
        - name: volume-permission-fix
          image: busybox:1.35
          command: ["sh", "-c", "mkdir -p /prometheus/data && chown -R 65534:65534 /prometheus/data"]
          volumeMounts:
            - name: prometheus-data
              mountPath: /prometheus/data
      containers:
        - name: {{ .Values.prometheus.name }}
          image: "{{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}"
          args:
            - "--config.file={{ .Values.prometheus.args.configFile }}"
            - "--storage.tsdb.retention.time={{ .Values.prometheus.args.retentionTime }}"
            - "--web.enable-admin-api"
          ports:
            - containerPort: {{ .Values.prometheus.ports.containerPort }}
          volumeMounts:
            - name: config-volume
              mountPath: {{ .Values.prometheus.volumeMounts.config.mountPath }}
            - name: prometheus-data
              mountPath: {{ .Values.prometheus.volumeMounts.data.mountPath }}
          resources:
            {{- toYaml .Values.prometheus.resources | nindent 12 }}
      volumes:
        - name: prometheus-data
          hostPath:
            path: /Users/emabhiza/Dev/webistecs-storage/prometheus-data
            type: DirectoryOrCreate
        - name: config-volume
          configMap:
            name: {{ .Values.prometheus.configMap.name }}