apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: monitoring
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    clients:
      - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push

    scrape_configs:
      - job_name: kubernetes-logs
        static_configs:
          - targets: ['localhost']
            labels:
              job: kubernetes-logs
              __path__: /var/log/containers/webistecs*.log
        pipeline_stages:
          - regex:
              expression: "^(?P<pod>[^_]+)_(?P<namespace>[^_]+)_(?P<container>[^_]+)(?:-[a-f0-9]+)?\\.log$"
              source: __path__
              target: filename_data
          - template:
              source: 'Extracted data: {{ toJson .filename_data }}'
              target: debug_output
          - labels:
              pod: '{{ if .filename_data.pod }}{{ .filename_data.pod }}{{ else }}unknown{{ end }}'
              namespace: '{{ if .filename_data.namespace }}{{ .filename_data.namespace }}{{ else }}unknown{{ end }}'
              container: '{{ if .filename_data.container }}{{ .filename_data.container }}{{ else }}unknown{{ end }}'
          - multiline:
              firstline: '^\['
              max_wait_time: 3s
          - regex:
              expression: '^\[(?P<time>\d{2}:\d{2}:\d{2}) (?P<level>\w{3})\] \[(?P<category>[^\]]+)\](?: \[(?P<app>[^\]]+)\])? (?P<msg>.+)$'
              source: message
          - regex:
              expression: '.*http request (?:success|failure) (?P<http_status>\d{3}).*'
              source: msg
          - labels:
              http_status: '{{ if .http_status }}{{ .http_status }}{{ else }}unknown{{ end }}'
          - regex:
              expression: '^(?P<exception>.*(Exception|Error).*)$'
              source: msg
              target: exception_info
          - labels:
              exception: '{{ if .exception_info.exception }}true{{ else }}false{{ end }}'
          - timestamp:
              source: time
              format: "15:04:05"
              target: __timestamp__
          - output:
              source: "[{{ .time }} {{ .level }}] [{{ .category }}]{{ if .app }} [{{ .app }}]{{ end }} {{ .msg }}"