apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.prometheus.configMap.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    mylabel: {{ .Values.prometheus.configMap.labels.mylabel }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.scrapeInterval }}

    scrape_configs:
      - job_name: '{{ .Values.prometheus.configMap.scrapeConfigs.kubernetesPods }}'
        kubernetes_sd_configs:
          - role: pod

      - job_name: '{{ .Values.prometheus.configMap.scrapeConfigs.kubeStateMetrics }}'
        kubernetes_sd_configs:
          - role: service
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name]
            action: keep
            regex: kube-system;kube-state-metrics

      - job_name: '{{ .Values.prometheus.configMap.scrapeConfigs.coinmarketcapExporter }}'
        static_configs:
          - targets: ['{{ .Values.prometheus.configMap.scrapeConfigs.coinmarketcapExporterTarget }}']

      - job_name: '{{ .Values.prometheus.configMap.scrapeConfigs.websitecs }}'
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_mylabel]
            target_label: websitecs
        static_configs:
          - targets: ['{{ .Values.prometheus.configMap.scrapeConfigs.websitecsTarget }}']

      - job_name: '{{ .Values.prometheus.configMap.scrapeConfigs.nodeExporter }}'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name]
            action: keep
            regex: monitoring;node-exporter
