apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-config
  namespace: monitoring
data:
  vector.toml: |
    [sources.my_logs]
    type = "file"
    include = ["/var/log/containers/simplified*.log"]
    ignore_older = 86400
    fingerprint.strategy = "device_and_inode"

    [transforms.parse]
    type = "remap"
    inputs = ["my_logs"]
    source = '''
    if is_string(.message) {
      . = merge(., parse_regex!(.message, r'^\[(?P<timestamp>[^\]]+)\] \[(?P<level>[^\]]+)\] (?P<message>.+)$'))
    } else {
      .
    }
    '''

    [sinks.console]
    type = "console"
    inputs = ["parse"]
    encoding.codec = "json"