apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vector
  namespace: monitoring
  labels:
    app: vector
spec:
  selector:
    matchLabels:
      app: vector
  template:
    metadata:
      labels:
        app: vector
    spec:
      serviceAccountName: vector
      containers:
        - name: vector
          image: timberio/vector:0.44.0-debian
          args: ["-c", "/etc/vector/vector.toml"]
          imagePullPolicy: IfNotPresent
          env:
            - name: VECTOR_LOG
              value: "info"
          resources:
            limits:
              memory: "200Mi"
              cpu: "100m"
            requests:
              memory: "100Mi"
              cpu: "50m"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/vector
            - name: vector-storage
              mountPath: /vector-logs
            - name: varlog
              mountPath: /var/log
      volumes:
        - name: config-volume
          configMap:
            name: vector-config
        - name: vector-storage
          hostPath:
            path: /media/emabhiza/webistecsStorage/webistecs/vector
            type: DirectoryOrCreate
        - name: varlog
          hostPath:
            path: /var/log