apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-db-migration"
  annotations:
    argocd.argoproj.io/hook: "{{ .Values.dbMigrationJob.annotations.argocd.hook }}"
    argocd.argoproj.io/hook-weight: "{{ .Values.dbMigrationJob.annotations.argocd.hookWeight }}"
    argocd.argoproj.io/hook-delete-policy: "{{ .Values.dbMigrationJob.annotations.argocd.hookDeletePolicy }}"
    image-tag: "{{ .Values.dbMigrationJob.image.tag | quote }}"
    image: "{{ .Values.dbMigrationJob.image.repository }}:{{ .Values.dbMigrationJob.image.tag | quote }}"
    checksum/config: "{{ .Values.dbMigrationJob.image.tag | sha256sum }}"
    rollme: "{{ randAlphaNum 5 | quote }}"
spec:
  template:
    metadata:
      labels:
        job: "db-migration"
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: migration
          image: "{{ .Values.dbMigrationJob.image.repository }}:{{ .Values.dbMigrationJob.image.tag | quote }}"
          imagePullPolicy: Always
          env:
            - name: ASPNETCORE__ENVIRONMENT
              value: "{{ .Values.dbMigrationJob.environment.aspNetCoreEnvironment }}"
            - name: ConnectionStrings__WebistecsContext
              value: "{{ .Values.dbMigrationJob.environment.webistecsContext }}"
          resources:
            requests:
              memory: "{{ .Values.dbMigrationJob.resources.requests.memory }}"
              cpu: "{{ .Values.dbMigrationJob.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.dbMigrationJob.resources.limits.memory }}"
              cpu: "{{ .Values.dbMigrationJob.resources.limits.cpu }}"
          volumeMounts:
            - name: db-storage
              mountPath: /db
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: webistecs-db-pvc
      restartPolicy: Never