apiVersion: v1
kind: Service
metadata:
  name: webistecs-service
  labels:
    {{- include "webistecs.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: "http"
      port: 8000
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
  selector:
    {{- include "webistecs.selectorLabels" . | nindent 4 }}
