apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: myrepo/migration, myrepo/websitecs
    argocd-image-updater.argoproj.io/myrepo.migration.update-strategy: latest
    argocd-image-updater.argoproj.io/myrepo.websitecs.update-strategy: latest
    argocd-image-updater.argoproj.io/myrepo.migration.allow-tags: regexp:^beta-[0-9]+\.[0-9]+$
    argocd-image-updater.argoproj.io/myrepo.websitecs.allow-tags: regexp:^beta-[0-9]+\.[0-9]+$
    checksum/config: "{{ printf "%s:%s" .Values.webistecs.image.repository .Values.webistecs.image.tag | sha256sum }}"


spec:
  replicas: {{ .Values.webistecs.replicaCount }}
  selector:
    matchLabels:
      {{- include "webistecs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "webistecs.selectorLabels" . | nindent 8 }}
      annotations:
        co.elastic.logs/enabled: {{ .Values.webistecs.logging.enabled | quote }}
        co.elastic.logs/module: {{ .Values.webistecs.logging.module | quote }}
        co.elastic.logs/fileset.stdout: {{ .Values.webistecs.logging.fileset.stdout | quote }}
        co.elastic.logs/fileset.stderr: {{ .Values.webistecs.logging.fileset.stderr | quote }}
        checksum/config: "{{ printf "%s:%s" .Values.webistecs.image.repository .Values.webistecs.image.tag | sha256sum }}"
    spec:
      containers:
        - name: {{ .Values.webistecs.containerName }}
          image: "{{ .Values.webistecs.image.repository }}:{{ .Values.webistecs.image.tag }}"
          command: ["dotnet", "Trader/Trader.dll"]
          imagePullPolicy: {{ .Values.webistecs.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.webistecs.containerPort }}
          readinessProbe:
            httpGet:
              path: {{ .Values.webistecs.readinessProbe.path }}
              port: {{ .Values.webistecs.readinessProbe.port }}
            initialDelaySeconds: {{ .Values.webistecs.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.webistecs.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.webistecs.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.webistecs.readinessProbe.successThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .Values.webistecs.livenessProbe.path }}
              port: {{ .Values.webistecs.livenessProbe.port }}
            initialDelaySeconds: {{ .Values.webistecs.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.webistecs.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.webistecs.livenessProbe.failureThreshold }}
          env:
            - name: COINBASE__PRIVATEKEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.webistecs.secrets.webistecsSecret }}
                  key: {{ .Values.webistecs.secrets.coinbase__privateKey }}
            - name: COINBASE__PRIVATEKEYNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.webistecs.secrets.webistecsSecret }}
                  key: {{ .Values.webistecs.secrets.coinbase__privateName }}
            - name: KRAKEN__PUBLICKEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.webistecs.secrets.webistecsSecret }}
                  key: {{ .Values.webistecs.secrets.krakenPublicKey }}
            - name: KRAKEN__PRIVATEKEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.webistecs.secrets.webistecsSecret }}
                  key: {{ .Values.webistecs.secrets.krakenPrivateKey }}
            - name: TELEGRAM__TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.webistecs.secrets.webistecsSecret }}
                  key: {{ .Values.webistecs.secrets.telegramBotToken }}
            - name: TELEGRAM__CHANNELS__NOTIFICATIONS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.webistecs.secrets.webistecsSecret }}
                  key: {{ .Values.webistecs.secrets.telegram_NotificationChannel }}
            - name: TELEGRAM__CHANNELS__ERRORS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.webistecs.secrets.webistecsSecret }}
                  key: {{ .Values.webistecs.secrets.telegram_ErrorsChannel }}
            - name: TELEGRAM__CHANNELS__FUNCTIONS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.webistecs.secrets.webistecsSecret }}
                  key: {{ .Values.webistecs.secrets.telegram_FunctionsChannel }}
            - name: DATABASE_PATH
              value: {{ .Values.webistecs.databasePath }}
            - name: ENVIRONMENT
              value: {{ .Values.webistecs.environment.aspNetCoreEnvironment }}
            - name: ConnectionStrings__WebistecsContext
              value: {{ .Values.webistecs.environment.webistecsContext}}
          resources:
            requests:
              memory: "{{ .Values.webistecs.resources.requests.memory }}"
              cpu: "{{ .Values.webistecs.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.webistecs.resources.limits.memory }}"
              cpu: "{{ .Values.webistecs.resources.limits.cpu }}"
          volumeMounts:
            - name: db-volume
              mountPath: {{ .Values.webistecs.volumeMountPath }}
        - name: {{ .Values.nodeExporter.name }}
          image: "{{ .Values.nodeExporter.image }}"
          ports:
            - containerPort: {{ .Values.nodeExporter.containerPort }}
      restartPolicy: {{ .Values.webistecs.restartPolicy }}
      imagePullSecrets:
        - name: {{ .Values.webistecs.imagePullSecret }}
      volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName: {{ .Values.webistecs.volume.persistentVolumeClaim.claimName }}