# Deployment YAML
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.webistecs.nameOverride | default .Chart.Name }}
  labels:
    {{- include "webistecs.labels" . | nindent 4 }}
  annotations:
    docker-image: {{ .Values.webistecs.image.repository }}:{{ .Values.webistecs.image.tag }}
spec:
  replicas: {{ .Values.webistecs.replicaCount }}
  selector:
    matchLabels:
      {{- include "webistecs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "webistecs.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.webistecs.containerName }}
          image: "{{ .Values.webistecs.image.repository }}:{{ .Values.webistecs.image.tag }}"
          imagePullPolicy: {{ .Values.webistecs.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.webistecs.containerPort }}
          readinessProbe:
            httpGet:
              path: {{ .Values.webistecs.readinessProbe.path }}
              port: {{ .Values.webistecs.readinessProbe.port }}
            initialDelaySeconds: {{ .Values.webistecs.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.webistecs.readinessProbe.periodSeconds }}
          env:
            - name: COINBASE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.webistecs.secrets.coinbaseApiKeySecret }}
                  key: {{ .Values.webistecs.secrets.coinbaseApiKey }}
            - name: COINBASE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.webistecs.secrets.coinbaseApiSecretSecret }}
                  key: {{ .Values.webistecs.secrets.coinbaseApiSecret }}
            - name: DATABASE_PATH
              value: {{ .Values.webistecs.databasePath }}
            - name: ConnectionStrings__WebistecsContext
              value: {{ .Values.webistecs.environment.connectionStrings.webistecsContext }}
          resources:
            requests:
              memory: "{{ .Values.webistecs.resources.requests.memory }}"
              cpu: "{{ .Values.webistecs.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.webistecs.resources.limits.memory }}"
              cpu: "{{ .Values.webistecs.resources.limits.cpu }}"
          volumeMounts:
            - name: db-volume
              mountPath: {{ .Values.webistecs.volumeMountPath }}
        - name: {{ .Values.nodeExporter.name }}
          image: "{{ .Values.nodeExporter.image }}"
          ports:
            - containerPort: {{ .Values.nodeExporter.containerPort }}
      restartPolicy: {{ .Values.webistecs.restartPolicy }}
      imagePullSecrets:
        - name: {{ .Values.webistecs.imagePullSecret }}
      volumes:
        - name: db-volume
          hostPath:
            path: {{ .Values.webistecs.volume.hostPath }}
            type: {{ .Values.webistecs.volume.type }}
