apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-shared-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany # Use RWX to share, or RWO if same node
  hostPath:
    path: /Users/emabhiza/Dev/webistecs-storage/database
