# values.yaml
webistecs:
  nameOverride: "webistecs"
  replicaCount: 1
  containerName: "my-container"
  image:
    repository: docker.io/emabhiza/webistecs
    tag: test-app-1
  environment:
    aspNetCoreEnvironment: Production
    webistecsContext: "Data Source=/mnt/nfsshare/webistecs-database/local-webistecs.db"
  imagePullPolicy: "Always"
  containerPort: 80
  readinessProbe:
    path: "/healthz"
    port: 80
    initialDelaySeconds: 5
    periodSeconds: 10
  secrets:
    coinbaseApiKeySecret: "my-secret"
    coinbaseApiKey: "cb_apiKey"
    coinbaseApiSecretSecret: "my-secret"
    coinbaseApiSecret: "cb_apiSecret"
    coingeckoSecret: "my-secret"
    coingeckoApiKey: "coingecko_apiKey"
  databasePath: "/mnt/nfsshare/webistecs-database/local-webistecs.db"
  volumeMountPath: "/mnt/nfsshare"
  service:
    nodePortHttp: 30080
  restartPolicy: "Always"
  imagePullSecret: "myregistrykey"
  volume:
    hostPath: "/mnt/nfsshare"
    type: "DirectoryOrCreate"
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

nodeExporter:
  name: "node-exporter"
  image: "prom/node-exporter:latest"
  containerPort: 9100

env:
  ASPNETCORE_ENVIRONMENT: Production
  ConnectionStrings__DefaultConnection: Data Source=/mnt/nfsshare/webistecs-database/local-webistecs.db
  ConnectionStrings__WebistecsContext: Data Source=/mnt/nfsshare/webistecs-database/local-webistecs.db

dbMigrationJob:
  image:
    repository: emabhiza/webistecs-migrations
    tag: test-v1
  environment:
    aspNetCoreEnvironment: Production
    webistecsContext: "Data Source=/mnt/nfsshare/webistecs-database/local-webistecs.db"
  volumeMounts:
    - name: db-storage
      mountPath: /mnt/nfsshare/webistecs-database
  volumes:
    - name: db-storage
      persistentVolumeClaim:
        claimName: webistecs-db-pvc
  annotations:
    argocd:
      hook: PreSync
      hookWeight: "5"
      hookDeletePolicy: "BeforeHookCreation,HookSucceeded"
  resources:
    requests:
      memory: "1Gi"
      cpu: "1000m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

grafana:
  auth:
    disableLoginForm: false
  nameOverride: ""
  replicaCount: 1
  image:
    repository: grafana/grafana-enterprise
    tag: 11.0.0
  env:
    GF_LOG_LEVEL: info
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"
  configMapName: grafana-dashboard-provisioning
  service:
    type: NodePort
    port: 3000
    targetPort: 3000
    nodePort: 30091

grafanaPV:
  name: grafana-nfs-volume
  capacity:
    storage: 1Gi
  accessModes: ReadWriteOnce
  reclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    path: /mnt/nfsshare/grafana
    server: 192.168.68.107

grafanaPVC:
  name: grafana-nfs-claim
  storageClassName: nfs-storage
  accessModes: ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

prometheus:
  kubeStateMetrics:
    enabled: false
  nameOverride: ""
  replicaCount: 1
  image:
    repository: prom/prometheus
    tag: latest
  service:
    type: NodePort
    nodePort: 30090
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"

prometheusPVC:
  name: prometheus-nfs-claim
  storageClassName: nfs-storage
  accessModes: ReadWriteOnce
  size: 10Gi

prometheusPV:
  name: prometheus-nfs-volume
  size: 10Gi
  accessModes: ReadWriteOnce
  reclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    path: /mnt/nfsshare/prometheus
    server: 192.168.68.107
