webistecs:
  nameOverride: "webistecs"
  replicaCount: 1
  containerName: "my-container"
  image:
    repository: docker.io/emabhiza/webistecs
    tag: beta-0.50
  environment:
    aspNetCoreEnvironment: Production
    webistecsContext: "Data Source=/db/webistecs.db"
  imagePullPolicy: "Always"
  containerPort: 80
  readinessProbe:
    path: "/healthz/ready"  # Path to the health check endpoint
    port: 8080        # Port for the health check
    initialDelaySeconds: 5  # Wait 5 seconds before starting the probe
    periodSeconds: 10       # Check every 10 seconds
    failureThreshold: 3     # Mark as not ready after 3 failures
    successThreshold: 1     # Mark as ready after 1 success
  livenessProbe:
    path: "/healthz/live"  # Path to the health check endpoint
    port: 8080        # Port for the health check
    initialDelaySeconds: 15  # Wait 15 seconds before starting the probe
    periodSeconds: 10        # Check every 10 seconds
    failureThreshold: 3      # Restart the pod after 3 failures
  secrets:
    coingeckoApiKey: "coingecko_apiKey"
    coinbase__privateKey: "coinbase__privateKey"
    coinbase__privateName: "coinbase__privateName"
    krakenPublicKey: "kraken_publicKey"
    krakenPrivateKey: "kraken_privateKey"
    telegramBotToken: "telegram_botToken"
    telegram_NotificationChannel: "telegram_channelsNotifications"
    telegram_ErrorsChannel: "telegram_channelsErrors"
    telegram_FunctionsChannel: "telegram_channelsFunctions"
    webistecsSecret: "webistecs-secret"
  databasePath: "/db/webistecs.db"
  volumeMountPath: "/db"
  service:
    nodePortHttp: 30080
  restartPolicy: "Always"
  imagePullSecret: "myregistrykey"
  volume:
    persistentVolumeClaim:
      claimName: "webistecs-db-pvc"
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
  logging:
    enabled: "true"
    module: "docker"
    fileset:
      stdout: "true"

nodeExporter:
  name: "node-exporter"
  image: "prom/node-exporter:latest"
  containerPort: 9100


dbMigrationJob:
  image:
    repository: emabhiza/webistecs-migrations
    tag: beta-0.50
  environment:
    aspNetCoreEnvironment: Production
    webistecsContext: "Data Source=/db/webistecs.db"
  volumes:
    - name: db-storage
      persistentVolumeClaim:
        claimName: webistecs-db-pvc
  annotations:
    argocd:
      hook: PreSync
      hookWeight: "5"
      hookDeletePolicy: "BeforeHookCreation,HookSucceeded"
  resources:
    requests:
      memory: "1Gi"
      cpu: "1000m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

