# Disable main webistecs deployment
webistecs:
  enabled: false  # This disables webistecs-deployment.yaml
  # Keep other webistecs configs that are referenced elsewhere
  containerPort: 80  # Needed by service
  environment:
    aspNetCoreEnvironment: "Backtest"  # Needed by service

# Backtester configuration (enabled)
backtester:
  enabled: true
  image:
    repository: "docker.io/emabhiza/webistecs-backtest"
    tag: "test-0.0.1"
    pullPolicy: "Always"
  pvc: "pricadata-pvc"
  dataDir: "/app/pricadata"
  year: "2023"
  environment:
    webistecsContext: "Data Source=/db/webistecs-backtest.db"
  resources:
    requests:
      ephemeral-storage: "100Mi"
    limits:
      ephemeral-storage: "300Mi"

# Service configuration
service:
  enabled: true  # Keep service even if webistecs is disabled
  type: ClusterIP
  port: 8000

# Migration job
dbMigrationJob:
  enabled: true
  image:
    repository: "docker.io/emabhiza/webistecs-migrations"
    tag: "test-0.0.1"
  volumeClaimName: "webistecs-db-pvc"

# Shared configurations
imagePullSecrets:
  - name: "myregistrykey"