imageTag: &webistecsImageTag "test-0.0.1"

environment: "Production"
nameOverride: prod-webistecs

webistecs:
  enabled: true
  replicaCount: 1
  containerName: webistecs
  image:
    repository: "docker.io/emabhiza/webistecs"
    tag:  *webistecsImageTag
  readinessProbe:
    path: /healthz/ready
    port: 80
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 3
    successThreshold: 5
  livenessProbe:
    path: /healthz/live
    port: 80
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 5
  containerPort: 80
  imagePullPolicy: "Always"
  imagePullSecret: "myregistrykey"
  restartPolicy: "Always"
  application:
    environment: "Production"
  environment:
    ASPNETCORE_URLS: "http://0.0.0.0:80"
    aspNetCoreEnvironment: "Production"
    webistecsContext: "Host=postgresql-prod.default.svc.cluster.local;Port=5432;Database=webistecs;Username=myappuser;Password=mypassword"
  secrets:
    webistecsSecret: "webistecs-secret"
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
  logging:
    enabled: "true"
    module: "docker"
    fileset:
      stdout: "true"
      stderr: "false"

dbMigrationJob:
  image:
    repository: "docker.io/emabhiza/webistecs-migrations"
    tag:  *webistecsImageTag
  environment:
    aspNetCoreEnvironment: "Production"
    webistecsContext: "Host=postgresql-prod.default.svc.cluster.local;Port=5432;Database=webistecs;Username=myappuser;Password=mypassword"
    SKIP_MIGRATIONS: "false"
  imagePullSecret: myregistrykey
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1"

service:
  enabled: true
  type: ClusterIP
  port: 8000
  targetPort: 80

nodeExporter:
  name: node-exporter
  image: prom/node-exporter:latest
  containerPort: 9100

backtester:
  enabled: false