webistecs:
  replicaCount: 1
  containerName: "webistecs"
  image:
    repository: "docker.io/emabhiza/webistecs"
    tag: "v0.0.6"
  imagePullPolicy: "Always"
  environment:
    aspNetCoreEnvironment: Production
    webistecsContext: "Data Source=/db/webistecs.db"
  containerPort: 80
  readinessProbe:
    path: "/healthz/ready"
    port: 8080
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3
    successThreshold: 1
  livenessProbe:
    path: "/healthz/live"
    port: 8080
    initialDelaySeconds: 15
    periodSeconds: 10
    failureThreshold: 3
  secrets:
    webistecsSecret: "webistecs-secret"
    coinbase__privateKey: "coinbase__privateKey"
    coinbase__privateName: "coinbase__privateName"
  volumeMountPath: "/db"
  restartPolicy: "Always"
  imagePullSecret: "myregistrykey"
  volume:
    persistentVolumeClaim:
      claimName: "webistecs-db-pvc"
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
  logging:
    enabled: "true"
    module: "docker"
    fileset:
      stdout: "true"
      stderr: "false"

nodeExporter:
  name: "node-exporter"
  image: "prom/node-exporter:latest"
  containerPort: 9100

dbMigrationJob:
  image:
    repository: docker.io/emabhiza/webistecs-migrations
    tag: "v0.0.6"
  environment:
    aspNetCoreEnvironment: Production
    webistecsContext: "Data Source=/db/webistecs.db"
  volumes:
    - name: db-storage
      persistentVolumeClaim:
        claimName: webistecs-db-pvc
  annotations:
    argocd:
      hook: PreSync
      hookWeight: "5"
      hookDeletePolicy: "BeforeHookCreation,HookSucceeded"
  imagePullSecret: "myregistrykey"
  resources:
    requests:
      memory: "1Gi"
      cpu: "1000m"
    limits:
      memory: "1Gi"
      cpu: "1000m"