webistecs:
  enabled: false
  environment:
    aspNetCoreEnvironment: "Backtest"
  imagePullSecret: "myregistrykey"
  image:
    repository: "placeholder"
    tag: "placeholder"
  containerPort: 80
  imagePullPolicy: "Always"
  readinessProbe:
    path: "/healthz/ready"
    port: 80
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3
    successThreshold: 1
  livenessProbe:
    path: "/healthz/live"
    port: 80
    initialDelaySeconds: 15
    periodSeconds: 10
    failureThreshold: 3
  volumeMountPath: "/db"
  volume:
    persistentVolumeClaim:
      claimName: "placeholder-pvc"
  secrets:
    webistecsSecret: "placeholder-secret"
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "100m"
  logging:
    enabled: true
    module: "placeholder"
    fileset:
      stdout: "true"
      stderr: "false"

nodeExporter:
  name: "node-exporter"
  image: "prom/node-exporter:latest"
  containerPort: 9100


backtester:
  environment:
    aspNetCoreEnvironment: "Backtester"
    webistecsContext: "Data Source=/db/webistecs-backtest.db"
  image:
    repository: "docker.io/emabhiza/webistecs-backtest"
    tag: "test-0.0.1"
  pvc: "pricadata-pvc"
  dataDir: "/app/pricadata"
  year: "2023"



dbMigrationJob:
  image:
    repository: "docker.io/emabhiza/webistecs-migrations"
    tag: "test-0.0.1"
  environment:
    aspNetCoreEnvironment: "Backtester"
    webistecsContext: "Data Source=/db/webistecs-backtest.db"
  imagePullSecret: "myregistrykey"
  volumeClaimName: "webistecs-db-pvc"
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "250m"