webistecs:
  enabled: false
  fullnameOverride: "placeholder-disabled"
  image:
    repository: "placeholder"
    tag: "placeholder"
    pullPolicy: "IfNotPresent"
  containerName: "placeholder"
  containerPort: 80
  readinessProbe:
    path: "/healthz/ready"
    port: 80
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3
    successThreshold: 1
  livenessProbe:
    path: "/healthz/live"
    port: 80
    initialDelaySeconds: 15
    periodSeconds: 10
    failureThreshold: 3
  environment:
    aspNetCoreEnvironment: "disabled-placeholder"
    webistecsContext: ""
  volumeMountPath: "/db"
  volume:
    persistentVolumeClaim:
      claimName: "placeholder-pvc"
  secrets:
    webistecsSecret: "placeholder-secret"
  logging:
    enabled: false
    module: "placeholder"
    fileset:
      stdout: false
      stderr: false
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "100m"
  imagePullSecret: "placeholder-secret"
  restartPolicy: "Always"

backtester:
  enabled: true
  environment:
    aspNetCoreEnvironment: "Backtester"
    webistecsContext: "Data Source=/db/webistecs-backtest.db"
  image:
    repository: "docker.io/emabhiza/webistecs-backtest"
    tag: "test-0.0.1"
    pullPolicy: "Always"
  pvc: "pricadata-pvc"
  dataDir: "/app/pricadata"
  year: "2019"
  resources:
    requests:
      ephemeral-storage: "100Mi"
    limits:
      ephemeral-storage: "300Mi"

dbMigrationJob:
  enabled: true
  image:
    repository: "docker.io/emabhiza/webistecs-migrations"
    tag: "test-0.0.1"
  environment:
    aspNetCoreEnvironment: "Backtester"
    webistecsContext: "Data Source=/db/webistecs-backtest.db"
  imagePullSecret: "myregistrykey"
  volumeClaimName: "webistecs-db-pvc"
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "250m"

service:
  enabled: true
  type: ClusterIP
  port: 8000
  targetPort: 80
  nodePort: 30081

nodeExporter:
  enabled: false
  name: "node-exporter"
  image: "prom/node-exporter:latest"
  containerPort: 9100

imagePullSecrets:
  - name: "myregistrykey"
