# values-backtester.yaml
webistecs:
  enabled: false  # Completely disable main webistecs deployment
  fullnameOverride: ""  # Clear any naming overrides

# Backtester specific configuration
backtester:
  enabled: true
  
  # Environment variables
  environment:
    aspNetCoreEnvironment: "Backtester"
    webistecsContext: "Data Source=/db/webistecs-backtest.db"
  
  # Image configuration
  image:
    repository: "docker.io/emabhiza/webistecs-backtest"
    tag: "test-0.0.1"
    pullPolicy: "Always"
  
  # Storage configuration (only using pricadata-pvc)
  pvc: "pricadata-pvc"
  dataDir: "/app/pricadata"
  
  # Backtest parameters
  year: "2023"
  
  # Resources
  resources:
    requests:
      ephemeral-storage: "100Mi"
    limits:
      ephemeral-storage: "300Mi"

# Database migration job configuration
dbMigrationJob:
  enabled: true
  
  # Image configuration
  image:
    repository: "docker.io/emabhiza/webistecs-migrations"
    tag: "test-0.0.1"
    pullPolicy: "Always"
  
  # Storage (using separate PVC for DB)
  volumeClaimName: "webistecs-db-pvc"
  
  # Resources
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "250m"

# Registry configuration (shared)
imagePullSecrets:
  - name: "myregistrykey"

# Service configuration (explicitly disabled)
service:
  enabled: false

# Monitoring (disabled)
nodeExporter:
  enabled: false