webistecs:
  environment:
    aspNetCoreEnvironment: "Backtest"
  imagePullSecret: "myregistrykey"
  image:
    repository: "placeholder"
    tag: "placeholder"
  logging:
    enabled: true
    module: "placeholder"
    fileset:
      stdout: "true"
      stderr: "false"

backtester:
  environment:
    aspNetCoreEnvironment: "Backtester"
    webistecsContext: "Data Source=/db/webistecs-backtest.db"
  image:
    repository: "docker.io/emabhiza/webistecs-backtest"
    tag: "test-0.0.1"
  pvc: "pricadata-pvc"
  dataDir: "/app/pricadata"
  year: "2023"

