environment: "test"
nameOverride: test-webistecs

webistecs:
  enabled: true
  replicaCount: 1
  containerName: webistecs
  image:
    repository: "docker.io/emabhiza/webistecs"
    tag: "test-0.0.10"
  readinessProbe:
    path: /healthz/ready
    port: 80
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3
    successThreshold: 1
  livenessProbe:
    path: /healthz/live
    port: 80
    initialDelaySeconds: 15
    periodSeconds: 10
    failureThreshold: 3
    successThreshold: 1
  containerPort: 80
  imagePullPolicy: "Always"
  imagePullSecret: myregistrykey     
  restartPolicy: "Always"
  environment:
    ASPNETCORE_URLS: "http://0.0.0.0:80"
    aspNetCoreEnvironment: "Test"
    webistecsContext: "Host=postgresql-test-postgresql.default.svc.cluster.local;Port=5432;Database=webistecs-test;Username=myappuser;Password=mypassword"
  secrets:
    webistecsSecret: "webistecs-secret"
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
  logging:
    enabled: "true"
    module: "docker"
    fileset:
      stdout: "true"
      stderr: "false"

nodeExporter:
  name: node-exporter
  image: prom/node-exporter:latest
  containerPort: 9100

service:
  enabled: true
  type: ClusterIP
  port: 8000
  targetPort: 80
  nodePort: 30081

dbMigrationJob:
  image:
    repository: "docker.io/emabhiza/webistecs-migrations"
    tag: "test-0.0.10"
  environment:
    aspNetCoreEnvironment: "Test"
    webistecsContext: "Host=postgresql-test-postgresql.default.svc.cluster.local;Port=5432;Database=webistecs-test;Username=myappuser;Password=mypassword"
    SKIP_MIGRATIONS: "false"
  imagePullSecret: "myregistrykey"
  resources:
    requests:
      memory: "1Gi"
      cpu: "1000m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

backtester:
  enabled: false