webistecs:
  enabled: false
  fullnameOverride: "placeholder-disabled"
  image:
    repository: "placeholder"
    tag: "placeholder"
    pullPolicy: "IfNotPresent"
  containerName: "placeholder"
  containerPort: 80
  readinessProbe:
    path: "/healthz/ready"
    port: 80
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3
    successThreshold: 1
  livenessProbe:
    path: "/healthz/live"
    port: 80
    initialDelaySeconds: 15
    periodSeconds: 10
    failureThreshold: 3
  environment:
    aspNetCoreEnvironment: "disabled-placeholder"
    webistecsContext: ""
  volume:
    persistentVolumeClaim:
      claimName: "placeholder-pvc"
  secrets:
    webistecsSecret: "placeholder-secret"
  logging:
    enabled: false
    module: "placeholder"
    fileset:
      stdout: false
      stderr: false
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "100m"
  imagePullSecret: "placeholder-secret"
  restartPolicy: "Always"

nameOverride: backtester

backtester:
  enabled: true
  environment:
    aspNetCoreEnvironment: "Backtester"
    webistecsContext: "Host=192.168.68.105;Port=5432;Database=webistecs-backtest;Username=myappuser;Password=mypassword"
  image:
    repository: "docker.io/emabhiza/webistecs-backtest"
    tag: "test-0.0.2"
    pullPolicy: "Always"
  pvc: "pricadata-test-pvc"
  dataDir: "/app/pricadata"
  year: "2023"  # Default if not specified in combo
  month: "1"    # Default if not specified in combo
  fee: "0.001"
  safetyMargin: "0.05"
  initialUsdc: "1000"
  strategy: "MacroUptrend"
  resources:
    requests:
      cpu: "200m"
      memory: "300Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  combo:
    upper:
      start: "{{ .Values.combo.upper.start }}"
      end: "{{ .Values.combo.upper.end }}"
      target: "{{ .Values.combo.upper.target }}"
      weight: "{{ .Values.combo.upper.weight }}"
      tier: "{{ .Values.combo.upper.tier }}"
    middle:
      start: "{{ .Values.combo.middle.start }}"
      end: "{{ .Values.combo.middle.end }}"
      target: "{{ .Values.combo.middle.target }}"
      weight: "{{ .Values.combo.middle.weight }}"
      tier: "{{ .Values.combo.middle.tier }}"
    lower:
      start: "{{ .Values.combo.lower.start }}"
      end: "{{ .Values.combo.lower.end }}"
      target: "{{ .Values.combo.lower.target }}"
      weight: "{{ .Values.combo.lower.weight }}"
      tier: "{{ .Values.combo.lower.tier }}"

dbMigrationJob:
  enabled: true
  image:
    repository: "docker.io/emabhiza/webistecs-migrations"
    tag: "v0.0.1"
  environment:
    aspNetCoreEnvironment: "Backtester"
    webistecsContext: "Host=192.168.68.105;Port=5432;Database=webistecs-backtest;Username=myappuser;Password=mypassword"
    SKIP_MIGRATIONS: "true"
  imagePullSecret: "myregistrykey"
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "250m"

service:
  enabled: true
  type: ClusterIP
  port: 8000
  targetPort: 80
  nodePort: 30081

nodeExporter:
  enabled: false
  name: "node-exporter"
  image: "prom/node-exporter:latest"
  containerPort: 9100

imagePullSecrets:
  - name: "myregistrykey"
